#!/usr/bin/env python
# EditXT
# Copyright (c) 2007-2010 Daniel Miller <millerdev@gmail.com>
# 
# This file is part of EditXT, a programmer's text editor for Mac OS X,
# which can be found at http://editxt.org/.
# 
# EditXT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# EditXT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with EditXT.  If not, see <http://www.gnu.org/licenses/>.
import os
import sys
from subprocess import call

thisdir = os.path.dirname(os.path.abspath(__file__))

if "--nosy" in sys.argv:
    import editxt.test.nosy as nosy
    sys.argv.remove("--nosy")
    sys.argv.append("--test")
    nosy.start(root=os.path.join(thisdir, 'editxt'))
else:
    cmd = list(sys.argv) + ["--pdb"]
    cmd[0] = os.path.join(thisdir, "dist/EditXTDev.app/Contents/MacOS/EditXTDev")
    sys.exit(call(cmd))
