# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: accesslog.js
name = 'Access log'
file_patterns = ['*.accesslog']

number = [RE(r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d{1,5})?\b")]

number0 = [RE(r"\b\d+\b")]

keyword = [
    'GET',
    'POST',
    'HEAD',
    'PUT',
    'DELETE',
    'CONNECT',
    'OPTIONS',
    'PATCH',
    'TRACE',
]

class string:
    default_text = DELIMITER
    word_groups = [('keyword', keyword)]

word_groups = [('number', number), ('number', number0)]

delimited_ranges = [
    ('string', RE(r"\"(GET|POST|HEAD|PUT|DELETE|CONNECT|OPTIONS|PATCH|TRACE)"), [RE(r"\"")], string),
    ('string', RE(r"\["), [RE(r"\]")]),
    ('string', RE(r"\""), [RE(r"\"")]),
]
