# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: actionscript.js
name = 'ActionScript'
file_patterns = ['*.actionscript', '*.as']

literal = ['true', 'false', 'null', 'undefined']

keyword = [
    'as',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'default',
    'delete',
    'do',
    'dynamic',
    'each',
    'else',
    'extends',
    'final',
    'finally',
    'for',
    'function',
    'get',
    'if',
    'implements',
    'import',
    'in',
    'include',
    'instanceof',
    'interface',
    'internal',
    'is',
    'namespace',
    'native',
    'new',
    'override',
    'package',
    'private',
    'protected',
    'public',
    'return',
    'set',
    'static',
    'super',
    'switch',
    'this',
    'throw',
    'try',
    'typeof',
    'use',
    'var',
    'void',
    'while',
    'with',
]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

number = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

keyword0 = ['package']

title = [RE(r"[a-zA-Z]\w*")]

class class0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('title', title)]
class0.__name__ = 'class'

keyword1 = ['class', 'interface']

class class1:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1), ('title', title)]
    delimited_ranges = [('_group4', RE(r"\b(extends|implements)"), [RE(r"\B|\b")])]
class1.__name__ = 'class'

keyword2 = ['function']

class params:
    default_text = DELIMITER
    delimited_ranges = [
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('rest_arg', RE(r"[.]{3}"), [RE(r"[a-zA-Z_$][a-zA-Z0-9_$]*")]),
    ]

class function:
    default_text = DELIMITER
    word_groups = [('keyword', keyword2), ('title', title)]
    delimited_ranges = [('params', RE(r"\("), [RE(r"\)")], params)]

word_groups = [('literal', literal), ('keyword', keyword), ('number', number)]

delimited_ranges = [
    ('string', RE(r"'"), [RE(r"'")]),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('comment', RE(r"//"), [RE(r"$")], comment),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('class', RE(r"\b(package)"), [RE(r"{")], class0),
    ('class', RE(r"\b(class|interface)"), [RE(r"(?={)")], class1),
    ('meta', RE(r"\b(import|include)"), [RE(r";")]),
    ('function', RE(r"\b(function)"), [RE(r"(?=[{;])")], function),
]
