# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: apache.js
name = 'Apache'
file_patterns = ['*.apache', '*.apacheconf']

flags = re.IGNORECASE | re.MULTILINE

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

nomarkup = """
    order deny allow setenv rewriterule rewriteengine rewritecond
    documentroot sethandler errordocument loadmodule options header
    listen serverroot servername
    """.split()

class attribute:
    default_text_color = DELIMITER
    rules = [('nomarkup', nomarkup)]

class attribute1:
    default_text_color = DELIMITER
    rules = [
        ('nomarkup', nomarkup),
        ('attribute', RE(r"\w+"), [RE(r"\B|\b")], attribute),
    ]
attribute1.__name__ = 'attribute'

number = ('number', [RE(r"[\$%]\d+")])

class variable:
    default_text_color = DELIMITER
    rules = [number]

class string:
    default_text_color = DELIMITER
    rules = [('operator.escape', [RE(r"\\[\s\S]")])]

class _group1:
    default_text_color = DELIMITER
    rules = [
        ('literal', ['on', 'off', 'all']),
        ('meta', RE(r"\s\["), [RE(r"\]$")]),
        ('variable', RE(r"[\$%]\{"), [RE(r"\}")], variable),
        number,
        ('string', RE(r"\""), [RE(r"\"")], string),
    ]

rules = [
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('section', RE(r"</?"), [RE(r">")]),
    ('attribute', attribute1, [RE(r"$")], _group1),
]
