# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: apache.js
name = 'Apache'
file_patterns = ['*.apache', '*.apacheconf']

flags = re.IGNORECASE | re.MULTILINE

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

nomarkup = [
    'order',
    'deny',
    'allow',
    'setenv',
    'rewriterule',
    'rewriteengine',
    'rewritecond',
    'documentroot',
    'sethandler',
    'errordocument',
    'loadmodule',
    'options',
    'header',
    'listen',
    'serverroot',
    'servername',
]

class attribute:
    default_text = DELIMITER
    word_groups = [('nomarkup', nomarkup)]

class attribute0:
    default_text = DELIMITER
    delimited_ranges = [('attribute', RE(r"\w+"), [RE(r"\B|\b")], attribute)]
attribute0.__name__ = 'attribute'

literal = ['on', 'off', 'all']

number = [RE(r"[\$%]\d+")]

class variable:
    default_text = DELIMITER
    word_groups = [('number', number)]

class _group1:
    default_text = DELIMITER
    word_groups = [('literal', literal), ('number', number)]
    delimited_ranges = [
        ('meta', RE(r"\s\["), [RE(r"\]$")]),
        ('variable', RE(r"[\$%]\{"), [RE(r"\}")], variable),
        ('string', RE(r"\""), [RE(r"\"")]),
    ]

word_groups = []

delimited_ranges = [
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('section', RE(r"</?"), [RE(r">")]),
    ('attribute', attribute0, [RE(r"(?=\B|\b)")], _group1),
]
