# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: asciidoc.js
name = 'AsciiDoc'
file_patterns = ['*.asciidoc', '*.adoc']

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

title = [RE(r"^\.\w.*$")]

section = [RE(r"^(={1,5}) .+?( \1)?$")]

section0 = [RE(r"^[^\[\]\n]+?\n[=\-~\^\+]{2,}$")]

meta = [RE(r"^\[.+?\]$")]

class _group3:
    default_text = DELIMITER
    delimited_ranges = [('_group4', RE(r"<"), [RE(r">")], 'xml')]

bullet = [RE(r"^(\*+|\-+|\.+|[^\n]+?::)\s+")]

symbol = [RE(r"^(NOTE|TIP|IMPORTANT|WARNING|CAUTION):\s+")]

string = [RE(r"``.+?''")]

string0 = [RE(r"`.+?'")]

code = [RE(r"(`.+?`|\+.+?\+)")]

class _group8:
    default_text = DELIMITER
    delimited_ranges = [
        ('link', RE(r"\w"), [RE(r"[^\[]+")]),
        ('string', RE(r"\["), [RE(r"(?=\])")]),
    ]

word_groups = [
    ('title', title),
    ('section', section),
    ('section', section0),
    ('meta', meta),
    ('bullet', bullet),
    ('symbol', symbol),
    ('string', string),
    ('string', string0),
    ('code', code),
]

delimited_ranges = [
    ('comment', RE(r"^/{4,}\n"), [RE(r"\n/{4,}$")], comment),
    ('comment', RE(r"^//"), [RE(r"$")], comment),
    ('_group2', RE(r"^[=\*]{4,}\n"), [RE(r"\n^[=\*]{4,}$")]),
    ('meta', RE(r"^:.+?:"), [RE(r"(?=\s)")]),
    ('quote', RE(r"^_{4,}\n"), [RE(r"\n_{4,}$")]),
    ('code', RE(r"^[\-\.]{4,}\n"), [RE(r"\n[\-\.]{4,}$")]),
    ('_group3', RE(r"^\+{4,}\n"), [RE(r"\n\+{4,}$")], _group3),
    ('strong', RE(r"\B\*(?![\*\s])"), [RE(r"(\n{2}|\*)")]),
    ('emphasis', RE(r"\B'(?!['\s])"), [RE(r"(\n{2}|')")]),
    ('emphasis', RE(r"_(?![_\s])"), [RE(r"(\n{2}|_)")]),
    ('code', RE(r"^[ \t]"), [RE(r"$")]),
    ('_group8', RE(r"(?=(link:)?(http|https|ftp|file|irc|image:?):\S+\[.*?\])"), [RE(r"\B|\b")], _group8),
]
