# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: autohotkey.js
name = 'AutoHotkey'
file_patterns = ['*.autohotkey']

flags = re.IGNORECASE | re.MULTILINE

literal = ['A', 'true', 'false', 'NOT', 'AND', 'OR']

keyword = ['Break', 'Continue', 'Else', 'Gosub', 'If', 'Loop', 'Return', 'While']

built_in = [RE(r"A_[a-zA-Z0-9]+")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

number = [RE(r"\b\d+(\.\d+)?")]

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('built_in', built_in),
    ('number', number),
]

delimited_ranges = [
    ('built_in', RE(r"\b(ComSpec|Clipboard|ClipboardAll|ErrorLevel)"), [RE(r"\B|\b")]),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('comment', RE(r";"), [RE(r"$")], comment),
    ('variable', RE(r"%"), [RE(r"%")]),
    ('symbol', RE(r"^[^\n\";]+::(?!=)"), [RE(r"\B|\b")]),
    ('symbol', RE(r"^[^\n\";]+:(?!=)"), [RE(r"\B|\b")]),
]
