# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: bash.js
name = 'Bash'
file_patterns = ['*.bash', '*.sh', '*.zsh']

_ = ['-ne', '-eq', '-lt', '-gt', '-f', '-d', '-e', '-s', '-l', '-a']

built_in = """
    break cd continue eval exec exit export getopts hash pwd readonly
    return shift test times trap umask unset alias bind builtin caller
    command declare echo enable help let local logout mapfile printf
    read readarray source type typeset ulimit unalias set shopt autoload
    bg bindkey bye cap chdir clone comparguments compcall compctl
    compdescribe compfiles compgroups compquote comptags comptry
    compvalues dirs disable disown echotc echoti emulate fc fg float
    functions getcap getln history integer jobs kill limit log noglob
    popd print pushd pushln rehash sched setcap setopt stat suspend
    ttyctl unfunction unhash unlimit unsetopt vared wait whence where
    which zcompile zformat zftp zle zmodload zparseopts zprof zpty
    zregexparse zsocket zstyle ztcp
    """.split()

keyword = """
    if then else elif fi for while in do done case esac function
    """.split()

literal = ['true', 'false']

meta = [RE(r"^#![^\n]+sh\s*$")]

title = [RE(r"\w[\w\d_]*")]

class function:
    default_text = DELIMITER
    rules = [('title', title)]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    rules = [
        # {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

number = [RE(r"\b\d+(?:\.\d+)?")]

variable = [RE(r"\$[\w\d#@][\w\d_]*")]

variable0 = [RE(r"\$\{(?:.*?)}")]

class variable1:
    default_text = DELIMITER
    rules = [
        # {'begin': '\\\\[\\s\\S]', 'relevance': 0},
    ]
variable1.__name__ = 'variable'

class string:
    default_text = DELIMITER
    rules = [
        # {'begin': '\\\\[\\s\\S]', 'relevance': 0},
        ('variable', variable),
        ('variable', variable0),
        ('variable', RE(r"\$\("), [RE(r"\)")], variable1),
    ]

rules = [
    ('_', _),
    ('built_in', built_in),
    ('keyword', keyword),
    ('literal', literal),
    ('meta', meta),
    ('function', RE(r"(?=\w[\w\d_]*\s*\(\s*\)\s*\{)"), [RE(r"\B\b")], function),
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('number', number),
    ('string', RE(r"\""), [RE(r"\"")], string),
    ('string', RE(r"'"), [RE(r"'")]),
    ('variable', variable0),
]

# TODO merge "word_groups" and "delimited_ranges" into "rules" in editxt.syntax
assert "__obj" not in globals()
assert "__fixup" not in globals()
def __fixup(obj):
    groups = []
    ranges = []
    rules = getattr(obj, "rules", [])
    for i, rng in reversed(list(enumerate(rules))):
        if len(rng) == 2:
            groups.append(rng)
        else:
            assert len(rng) > 2, rng
            ranges.append(rng)
    return groups, ranges

class __obj:
    rules = globals().get("rules", [])
word_groups, delimited_ranges = __fixup(__obj)

for __obj in globals().values():
    if hasattr(__obj, "rules"):
        __obj.word_groups, __obj.delimited_ranges = __fixup(__obj)

del __obj, __fixup
