# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: brainfuck.js
name = 'Brainfuck'
file_patterns = ['*.brainfuck', '*.bf']

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

title = [RE(r"[\[\]]")]

string = [RE(r"[\.,]")]

literal = [RE(r"[\+\-]")]

class _group1:
    default_text = DELIMITER
    word_groups = [('literal', literal)]

word_groups = [('title', title), ('string', string), ('literal', literal)]

delimited_ranges = [
    ('comment', RE(r"[^\[\]\.,\+\-<> \r\n]"), [RE(r"(?=[\[\]\.,\+\-<> \r\n])")], comment),
    ('_group1', RE(r"(?=\+\+|\-\-)"), [RE(r"\B|\b")], _group1),
]
