# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: cal.js
name = 'C/AL'
file_patterns = ['*.cal']

flags = re.IGNORECASE | re.MULTILINE

literal = ['false', 'true']

keyword = [
    'div',
    'mod',
    'in',
    'and',
    'or',
    'not',
    'xor',
    'asserterror',
    'begin',
    'case',
    'do',
    'downto',
    'else',
    'end',
    'exit',
    'for',
    'if',
    'of',
    'repeat',
    'then',
    'to',
    'until',
    'while',
    'with',
    'var',
]

string = [RE(r"(#\d+)+")]

number = [RE(r"\b\d+(\.\d+)?(DT|D|T)")]

number0 = [RE(r"\b\d+(\.\d+)?")]

title = [RE(r"[a-zA-Z]\w*")]

keyword0 = ['procedure']

class params:
    default_text = DELIMITER
    word_groups = [('keyword', keyword), ('string', string)]
    delimited_ranges = [('string', RE(r"'"), [RE(r"'")])]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

class function:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('title', title)]
    delimited_ranges = [
        ('params', RE(r"\("), [RE(r"\)")], params),
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"\{"), [RE(r"\}")], comment),
        ('comment', RE(r"\(\*"), [RE(r"\*\)")], comment),
    ]

class class0:
    default_text = DELIMITER
    word_groups = [('title', title)]
    delimited_ranges = [('function', RE(r"\b(procedure)"), [RE(r"[:;]")], function)]
class0.__name__ = 'class'

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('string', string),
    ('number', number),
    ('number', number0),
]

delimited_ranges = [
    ('string', RE(r"'"), [RE(r"'")]),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('class', RE(r"(?=OBJECT (Table|Form|Report|Dataport|Codeunit|XMLport|MenuSuite|Page|Query) (\d+) ([^\r\n]+))"), [RE(r"\B|\b")], class0),
    ('function', RE(r"\b(procedure)"), [RE(r"[:;]")], function),
]
