# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: capnproto.js
name = 'Cap’n Proto'
file_patterns = ['*.capnproto', '*.capnp']

literal = ['true', 'false']

keyword = [
    'struct',
    'enum',
    'interface',
    'union',
    'group',
    'import',
    'using',
    'const',
    'annotation',
    'extends',
    'in',
    'of',
    'on',
    'as',
    'with',
    'from',
    'fixed',
]

built_in = [
    'Void',
    'Bool',
    'Int8',
    'Int16',
    'Int32',
    'Int64',
    'UInt8',
    'UInt16',
    'UInt32',
    'UInt64',
    'Float32',
    'Float64',
    'Text',
    'Data',
    'AnyPointer',
    'AnyStruct',
    'Capability',
    'List',
]

number = [RE(r"\b\d+(\.\d+)?")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

meta = [RE(r"@0x[\w\d]{16};")]

number0 = [RE(r"@\d+\b")]

keyword0 = ['struct', 'enum']

title = [RE(r"[a-zA-Z]\w*")]

class class0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('title', title)]
class0.__name__ = 'class'

keyword1 = ['interface']

class class1:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1), ('title', title)]
class1.__name__ = 'class'

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('built_in', built_in),
    ('number', number),
    ('meta', meta),
    ('number', number0),
]

delimited_ranges = [
    ('string', RE(r"\""), [RE(r"\"")]),
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('class', RE(r"\b(struct|enum)"), [RE(r"\{")], class0),
    ('class', RE(r"\b(interface)"), [RE(r"\{")], class1),
]
