# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: clojure-repl.js
name = 'Clojure REPL'
file_patterns = ['*.clojure-repl']

class meta:
    default_text_color = DELIMITER
    rules = [('meta', RE(r"^(?:[\w.-]+|\s*#_)=>"), [RE(r"\B|\b")])]

rules = [('meta', meta, [RE(r"$")], 'clojure')]
