# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: clojure-repl.js
name = 'Clojure REPL'
file_patterns = ['*.clojure-repl']

meta = [RE(r"^([\w.-]+|\s*#_)=>")]

word_groups = [('meta', meta)]

delimited_ranges = []
