# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: coffeescript.js
name = 'CoffeeScript'
file_patterns = ['*.coffeescript', '*.coffee', '*.cson', '*.iced']

built_in = """
    npm require console print module global window document
    """.split()

keyword = """
    in if for while finally new do return else break catch instanceof
    throw try this switch continue typeof delete debugger super then
    unless until loop of by when and or is isnt not
    """.split()

literal = ['true', 'false', 'null', 'undefined', 'yes', 'no', 'on', 'off']

number = [RE(r"\b(?:0b[01]+)")]

class number0:
    default_text_color = DELIMITER
    rules = [
        ('number', RE(r"(?:\b0[xX][a-fA-F0-9]+|(?:\b\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)"), [RE(r"\B|\b")]),
    ]
number0.__name__ = 'number'

class string:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '\\\\[\\s\\S]', 'relevance': 0},
    ]

regexp = [RE(r"//[gim]*")]

regexp0 = [RE(r"\/(?![ *])(?:\\\/|.)*?\/[gim]*(?=\W|$)")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

class regexp1:
    default_text_color = DELIMITER
    rules = [
        None,  # string0.rules[1],
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]
regexp1.__name__ = 'regexp'

class subst:
    default_text_color = DELIMITER
    rules = [
        ('built_in', built_in),
        ('keyword', keyword),
        ('literal', literal),
        ('number', number),
        None,  # rules[4],
        None,  # rules[5],
        None,  # rules[6],
        None,  # rules[7],
        None,  # rules[8],
        ('regexp', RE(r"///"), [RE(r"///")], regexp1),
        ('regexp', regexp),
        ('regexp', regexp0),
        # ignore {'begin': '@[A-Za-z$_][0-9A-Za-z$_]*'},
        ('_group3', RE(r"`"), [RE(r"`")], 'javascript'),
    ]

class string0:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '\\\\[\\s\\S]', 'relevance': 0},
        ('subst', RE(r"#\{"), [RE(r"}")], subst),
    ]
string0.__name__ = 'string'

title = [RE(r"[A-Za-z$_][0-9A-Za-z$_]*")]

class _group4:
    default_text_color = DELIMITER
    rules = [
        ('built_in', built_in),
        ('keyword', keyword),
        ('literal', literal),
        ('number', number),
        None,  # rules[4],
        None,  # rules[5],
        None,  # rules[6],
        None,  # rules[7],
        None,  # rules[8],
        subst.rules[6],
        subst.rules[7],
        subst.rules[8],
        # ignore {'begin': '@[A-Za-z$_][0-9A-Za-z$_]*'},
        subst.rules[9],
    ]

class params:
    default_text_color = DELIMITER
    rules = [('_group4', RE(r"\("), [RE(r"\)")], _group4)]

class function:
    default_text_color = DELIMITER
    rules = [
        ('title', title),
        ('params', RE(r"(?=\([^\(])"), [RE(r"\B\b")], params),
    ]

class function0:
    default_text_color = DELIMITER
    rules = [function.rules[1]]
function0.__name__ = 'function'

class _group0:
    default_text_color = DELIMITER
    rules = [
        ('function', RE(r"(?=(?:\(.*\))?\s*\B[-=]>)"), [RE(r"[-=]>")], function0),
    ]

keyword0 = ['class']

keyword1 = ['extends']

class _group5:
    default_text_color = DELIMITER
    rules = [('keyword', keyword1), ('title', title)]

class class0:
    default_text_color = DELIMITER
    rules = [
        ('keyword', keyword0),
        ('_group5', RE(r"\b(?:extends)"), [RE(r"\B\b")], _group5),
        ('title', title),
    ]
class0.__name__ = 'class'

rules = [
    ('built_in', built_in),
    ('keyword', keyword),
    ('literal', literal),
    ('number', number),
    ('number', number0, [RE(r"(?:\s*/)?")]),
    ('string', RE(r"'''"), [RE(r"'''")], string),
    ('string', RE(r"'"), [RE(r"'")], string),
    ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string0),
    ('string', RE(r"\""), [RE(r"\"")], string0),
    subst.rules[6],
    subst.rules[7],
    subst.rules[8],
    # ignore {'begin': '@[A-Za-z$_][0-9A-Za-z$_]*'},
    subst.rules[9],
    ('comment', RE(r"###"), [RE(r"###")], comment),
    regexp1.rules[1],
    ('function', RE(r"(?=^\s*[A-Za-z$_][0-9A-Za-z$_]*\s*=\s*(?:\(.*\))?\s*\B[-=]>)"), [RE(r"[-=]>")], function),
    ('_group0', RE(r"[:\(,=]\s*"), [RE(r"\B\b")], _group0),
    ('class', RE(r"\b(?:class)"), [RE(r"$")], class0),
    ('_group1', RE(r"(?=[A-Za-z$_][0-9A-Za-z$_]*:)"), [RE(r"(?=:)")]),
]

regexp1.rules[0] = string0.rules[1]
subst.rules[4] = rules[4]
subst.rules[5] = rules[5]
subst.rules[6] = rules[6]
subst.rules[7] = rules[7]
subst.rules[8] = rules[8]
_group4.rules[4] = rules[4]
_group4.rules[5] = rules[5]
_group4.rules[6] = rules[6]
_group4.rules[7] = rules[7]
_group4.rules[8] = rules[8]
