# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: crmsh.js
name = 'crmsh'
file_patterns = ['*.crmsh', '*.crm', '*.pcmk']

flags = re.IGNORECASE | re.MULTILINE

keyword = """
    params meta operations op rule attributes utilization read write
    deny defined not_defined in_range date spec in ref reference
    attribute type xpath version and or lt gt tag lte gte eq ne \ number
    string
    """.split()

literal = """
    Master Started Slave Stopped start promote demote stop monitor true
    false
    """.split()

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

class _group0:
    default_text_color = DELIMITER
    rules = [('_group0', RE(r"\b(?:node)"), [RE(r"\B|\b")])]

class _group1:
    default_text_color = DELIMITER
    rules = [('_group1', _group0, [RE(r"\s*(?:[\w_-]+:)?")])]

class _group2:
    default_text_color = DELIMITER
    rules = [('_group2', RE(r"\b(?:primitive|rsc_template)"), [RE(r"\B|\b")])]

class title:
    default_text_color = DELIMITER
    rules = [('title', _group2, [RE(r"\s*[\$\w_][\w_-]*")])]

keyword0 = """
    group clone ms master location colocation order fencing_topology
    rsc_ticket acl_target acl_group user role tag xml
    """.split()

class _group4:
    default_text_color = DELIMITER
    rules = [('keyword', keyword0)]

class _group40:
    default_text_color = DELIMITER
    rules = [
        ('_group4', RE(r"\b(?:group|clone|ms|master|location|colocation|order|fencing_topology|rsc_ticket|acl_target|acl_group|user|role|tag|xml)\s+"), [RE(r"\B|\b")], _group4),
    ]
_group40.__name__ = '_group4'

class _group5:
    default_text_color = DELIMITER
    rules = [
        ('_group5', RE(r"\b(?:property|rsc_defaults|op_defaults)"), [RE(r"\B|\b")]),
    ]

class string:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '\\\\[\\s\\S]', 'relevance': 0},
    ]

meta = [RE(r"(?:ocf|systemd|service|lsb):[\w_:-]+")]

number = [RE(r"\b\d+(?:\.\d+)?(?:ms|s|h|m)?")]

literal0 = [RE(r"[-]?(?:infinity|inf)")]

attr = [RE(r"(?:[A-Za-z\$_\#][\w_-]+)=")]

rules = [
    ('keyword', keyword),
    ('literal', literal),
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('_group0', _group1, [RE(r"\s*[\$\w_][\w_-]*")]),
    ('_group2', title, [RE(r"\s*@?[\w_][\w_\.:-]*")]),
    ('_group4', _group40, [RE(r"[\$\w_][\w_-]*")]),
    ('_group5', _group5, [RE(r"\s*(?:[\w_-]+:)?")]),
    ('string', RE(r"\""), [RE(r"\"")], string),
    ('meta', meta),
    ('number', number),
    ('literal', literal0),
    ('attr', attr),
    ('tag', RE(r"</?"), [RE(r"/?>")]),
]
