# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: css.js
name = 'CSS'
file_patterns = ['*.css']

flags = re.IGNORECASE | re.MULTILINE

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

comment0 = ('comment', RE(r"/\*"), [RE(r"\*/")], comment)

class _group1:
    default_text_color = DELIMITER
    rules = [('keyword', ['font-face', 'page'])]

operator_escape = ('operator.escape', [RE(r"\\[\s\S]")])

class string:
    default_text_color = DELIMITER
    rules = [operator_escape]

string0 = ('string', RE(r"'"), [RE(r"'")], string)

string1 = ('string', RE(r"\""), [RE(r"\"")], string)

number = [
    RE(r"\b\d+(?:\.\d+)?(?:%|em|ex|ch|rem|vw|vh|vmin|vmax|cm|mm|in|pt|pc|px|deg|grad|rad|turn|s|ms|Hz|kHz|dpi|dpcm|dppx)?"),
]

number0 = ('number', number)

class _group3:
    default_text_color = DELIMITER
    ends_with_parent = True
    rules = [string0, string1, number0]

class _group2:
    default_text_color = DELIMITER
    rules = [
        ('keyword', [RE(r"\S+")]),
        ('_group3', RE(r"\s"), [RE(r"(?=[{;])")], _group3),
    ]

class _attribute0:
    default_text_color = DELIMITER
    rules = [('_attribute', [RE(r":")])]
_attribute0.__name__ = '_attribute'

class attribute0:
    default_text_color = DELIMITER
    rules = [('attribute', RE(r"\S"), [_attribute0])]
attribute0.__name__ = 'attribute'

class _group6:
    default_text_color = DELIMITER
    ends_with_parent = True
    rules = [
        number0,
        string1,
        string0,
        comment0,
        ('number', [RE(r"#[0-9A-Fa-f]+")]),
        ('meta', [RE(r"!important")]),
    ]

class _group5:
    default_text_color = DELIMITER
    ends_with_parent = True
    rules = [('attribute', attribute0, [RE(r"(?=;)")], _group6)]

class _group4:
    default_text_color = DELIMITER
    rules = [
        comment0,
        ('_group5', RE(r"(?=[A-Z\_\.\-]+\s*:)"), [RE(r";")], _group5),
    ]

rules = [
    comment0,
    ('selector-id', [RE(r"#[A-Za-z0-9_-]+")]),
    ('selector-class', [RE(r"\.[A-Za-z0-9_-]+")]),
    ('selector-attr', RE(r"\["), [RE(r"\]")]),
    ('selector-pseudo', [RE(r":(?::)?[a-zA-Z0-9\_\-\+\(\)\"']+")]),
    ('_group1', RE(r"@(?:font-face|page)"), [RE(r"\B|\b")], _group1),
    ('_group2', RE(r"@"), [RE(r"[{;]")], _group2),
    ('selector-tag', [RE(r"[a-zA-Z-][a-zA-Z0-9_-]*")]),
    ('_group4', RE(r"{"), [RE(r"}")], _group4),
]
