# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: dart.js
name = 'Dart'
file_patterns = ['*.dart']

literal = [
    'abstract',
    'as',
    'dynamic',
    'export',
    'external',
    'factory',
    'get',
    'implements',
    'import',
    'library',
    'operator',
    'part',
    'set',
    'static',
    'typedef',
]

keyword = [
    'assert',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'default',
    'do',
    'else',
    'enum',
    'extends',
    'false',
    'final',
    'finally',
    'for',
    'if',
    'in',
    'is',
    'new',
    'null',
    'rethrow',
    'return',
    'super',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'var',
    'void',
    'while',
    'with',
]

built_in = [
    'print',
    'Comparable',
    'DateTime',
    'Duration',
    'Function',
    'Iterable',
    'Iterator',
    'List',
    'Map',
    'Match',
    'Null',
    'Object',
    'Pattern',
    'RegExp',
    'Set',
    'Stopwatch',
    'String',
    'StringBuffer',
    'StringSink',
    'Symbol',
    'Type',
    'Uri',
    'bool',
    'double',
    'int',
    'num',
    'document',
    'window',
    'querySelector',
    'querySelectorAll',
    'Element',
    'ElementList',
]

keyword0 = ['true', 'false', 'null', 'this', 'is', 'new', 'super']

number = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

class subst:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0)]

class string:
    default_text = DELIMITER
    delimited_ranges = [('subst', RE(r"\$\{"), [RE(r"}")], subst)]

class subst0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('number', number)]
    delimited_ranges = [
        ('string', RE(r"r'''"), [RE(r"'''")]),
        ('string', RE(r"r\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"r'"), [RE(r"'")]),
        ('string', RE(r"r\""), [RE(r"\"")]),
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"'"), [RE(r"'")], string),
        ('string', RE(r"\""), [RE(r"\"")], string),
    ]
subst0.__name__ = 'subst'

class string0:
    default_text = DELIMITER
    delimited_ranges = [('subst', RE(r"\$\{"), [RE(r"}")], subst0)]
string0.__name__ = 'string'

class subst1:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('number', number)]
    delimited_ranges = [
        ('string', RE(r"r'''"), [RE(r"'''")]),
        ('string', RE(r"r\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"r'"), [RE(r"'")]),
        ('string', RE(r"r\""), [RE(r"\"")]),
        ('string', RE(r"'''"), [RE(r"'''")], string),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"'"), [RE(r"'")], string),
        ('string', RE(r"\""), [RE(r"\"")], string),
    ]
subst1.__name__ = 'subst'

class string1:
    default_text = DELIMITER
    delimited_ranges = [('subst', RE(r"\$\{"), [RE(r"}")], subst1)]
string1.__name__ = 'string'

class subst2:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('number', number)]
    delimited_ranges = [
        ('string', RE(r"r'''"), [RE(r"'''")]),
        ('string', RE(r"r\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"r'"), [RE(r"'")]),
        ('string', RE(r"r\""), [RE(r"\"")]),
        ('string', RE(r"'''"), [RE(r"'''")], string),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\""), [RE(r"\"")], string),
    ]
subst2.__name__ = 'subst'

class string2:
    default_text = DELIMITER
    delimited_ranges = [('subst', RE(r"\$\{"), [RE(r"}")], subst2)]
string2.__name__ = 'string'

class subst3:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('number', number)]
    delimited_ranges = [
        ('string', RE(r"r'''"), [RE(r"'''")]),
        ('string', RE(r"r\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"r'"), [RE(r"'")]),
        ('string', RE(r"r\""), [RE(r"\"")]),
        ('string', RE(r"'''"), [RE(r"'''")], string),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"'"), [RE(r"'")], string),
        ('string', RE(r"\""), [RE(r"\"")]),
    ]
subst3.__name__ = 'subst'

class string3:
    default_text = DELIMITER
    delimited_ranges = [('subst', RE(r"\$\{"), [RE(r"}")], subst3)]
string3.__name__ = 'string'

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

keyword1 = ['class', 'interface']

title = [RE(r"[a-zA-Z_]\w*")]

class class0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1), ('title', title)]
    delimited_ranges = [('_group20', RE(r"\b(extends|implements)"), [RE(r"\B|\b")])]
class0.__name__ = 'class'

annotation = [RE(r"@[A-Za-z]+")]

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('built_in', built_in),
    ('number', number),
    ('annotation', annotation),
]

delimited_ranges = [
    ('string', RE(r"r'''"), [RE(r"'''")]),
    ('string', RE(r"r\"\"\""), [RE(r"\"\"\"")]),
    ('string', RE(r"r'"), [RE(r"'")]),
    ('string', RE(r"r\""), [RE(r"\"")]),
    ('string', RE(r"'''"), [RE(r"'''")], string0),
    ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string1),
    ('string', RE(r"'"), [RE(r"'")], string2),
    ('string', RE(r"\""), [RE(r"\"")], string3),
    ('comment', RE(r"/\*\*"), [RE(r"\*/")], comment),
    ('comment', RE(r"///"), [RE(r"$")], comment),
    ('comment', RE(r"//"), [RE(r"$")], comment),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('class', RE(r"\b(class|interface)"), [RE(r"(?={)")], class0),
]
