# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: dart.js
name = 'Dart'
file_patterns = ['*.dart']

built_in = """
    print Comparable DateTime Duration Function Iterable Iterator List
    Map Match Null Object Pattern RegExp Set Stopwatch String
    StringBuffer StringSink Symbol Type Uri bool double int num document
    window querySelector querySelectorAll Element ElementList
    """.split()

keyword = """
    assert break case catch class const continue default do else enum
    extends false final finally for if in is new null rethrow return
    super switch this throw true try var void while with abstract as
    dynamic export external factory get implements import library
    operator part set static typedef
    """.split()

keyword0 = ['true', 'false', 'null', 'this', 'is', 'new', 'super']

number = [
    RE(r"(?:\b0[xX][a-fA-F0-9]+|(?:\b\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)"),
]

class subst:
    default_text_color = DELIMITER
    rules = [
        ('keyword', keyword0),
        ('number', number),
        None,  # rules[2],
        None,  # rules[3],
        None,  # rules[4],
        None,  # rules[5],
        None,  # rules[6],
        None,  # rules[7],
        None,  # rules[8],
        None,  # rules[9],
    ]

class string:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '\\\\[\\s\\S]', 'relevance': 0},
        ('subst', RE(r"\$\{"), [RE(r"}")], subst),
    ]

class string0:
    default_text_color = DELIMITER
    rules = [
        # ('contains', 0, 'variants', 4, 'contains', 0) {'begin': '\\\\[\\s\\S]', 'relevance': 0},
        string.rules[0],
    ]
string0.__name__ = 'string'

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

class _class:
    default_text_color = DELIMITER
    rules = [('_class', [RE(r"{")])]

keyword1 = ['class', 'interface']

title = [RE(r"[a-zA-Z_]\w*")]

class class0:
    default_text_color = DELIMITER
    rules = [
        ('keyword', keyword1),
        ('_group0', RE(r"\b(?:extends|implements)"), [RE(r"\B\b")]),
        ('title', title),
    ]
class0.__name__ = 'class'

meta = [RE(r"@[A-Za-z]+")]

rules = [
    ('built_in', built_in),
    ('keyword', keyword),
    ('string', RE(r"r'''"), [RE(r"'''")]),
    ('string', RE(r"r\"\"\""), [RE(r"\"\"\"")]),
    ('string', RE(r"r'"), [RE(r"'")]),
    ('string', RE(r"r\""), [RE(r"\"")]),
    ('string', RE(r"'''"), [RE(r"'''")], string),
    ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string0),
    ('string', RE(r"'"), [RE(r"'")], string0),
    ('string', RE(r"\""), [RE(r"\"")], string0),
    ('comment', RE(r"/\*\*"), [RE(r"\*/")], 'markdown'),
    ('comment', RE(r"///"), [RE(r"$")], 'markdown'),
    ('comment', RE(r"//"), [RE(r"$")], comment),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('class', RE(r"\b(?:class|interface)"), [_class], class0),
    ('number', number),
    ('meta', meta),
    # ignore {'begin': '=>'},
]

subst.rules[2] = rules[2]
subst.rules[3] = rules[3]
subst.rules[4] = rules[4]
subst.rules[5] = rules[5]
subst.rules[6] = rules[6]
subst.rules[7] = rules[7]
subst.rules[8] = rules[8]
subst.rules[9] = rules[9]
