# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: delphi.js
name = 'Delphi'
file_patterns = ['*.delphi']

flags = re.IGNORECASE | re.MULTILINE

keyword = """
    exports register file shl array record property for mod while set
    ally label uses raise not stored class safecall var interface or
    private static exit index inherited to else stdcall override shr asm
    far resourcestring finalization packed virtual out and protected
    library do xorwrite goto near function end div overload object unit
    begin string on inline repeat until destructor write message program
    with read initialization except default nil if case cdecl in downto
    threadvar of try pascal const external constructor type public then
    implementation finally published procedure
    """.split()

#class string:
#    default_text_color = DELIMITER
#    rules = [
#        # ignore {'begin': {'pattern': "''", 'type': 'RegExp'}},
#    ]

string0 = ('string', RE(r"'"), [RE(r"'")]) #, string)

string1 = ('string', [RE(r"(?:#\d+)+")])

title = ('title', [RE(r"[a-zA-Z]\w*")])

class _group1:
    default_text_color = DELIMITER
    rules = [title]

class params:
    default_text_color = DELIMITER
    rules = [('keyword', keyword), string0, string1]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

comment0 = ('comment', RE(r"//"), [RE(r"$")], comment)

comment1 = ('comment', RE(r"\{"), [RE(r"\}")], comment)

comment2 = ('comment', RE(r"\(\*"), [RE(r"\*\)")], comment)

class function:
    default_text_color = DELIMITER
    rules = [
        ('keyword', ['function', 'constructor', 'destructor', 'procedure']),
        ('keyword', ['function', 'constructor', 'destructor', 'procedure']),
        title,
        ('params', RE(r"\("), [RE(r"\)")], params),
        comment0,
        comment1,
        comment2,
    ]

rules = [
    ('keyword', keyword),
    string0,
    string1,
    ('number', [RE(r"\b\d+(?:\.\d+)?")]),
    ('_group1', RE(r"(?=[a-zA-Z]\w*\s*=\s*class\s*\()"), [RE(r"\B\b")], _group1),
    ('function', RE(r"\b(?:function|constructor|destructor|procedure)"), [RE(r"[:;]")], function),
    comment0,
    comment1,
    comment2,
]
