# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: django.js
name = 'Django'
file_patterns = ['*.django', '*.jinja']

flags = re.IGNORECASE | re.MULTILINE

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

keyword = [
    'comment',
    'endcomment',
    'load',
    'templatetag',
    'ifchanged',
    'endifchanged',
    'if',
    'endif',
    'firstof',
    'for',
    'endfor',
    'ifnotequal',
    'endifnotequal',
    'widthratio',
    'extends',
    'include',
    'spaceless',
    'endspaceless',
    'regroup',
    'ifequal',
    'endifequal',
    'ssi',
    'now',
    'with',
    'cycle',
    'url',
    'filter',
    'endfilter',
    'debug',
    'block',
    'endblock',
    'else',
    'autoescape',
    'endautoescape',
    'csrf_token',
    'empty',
    'elif',
    'endwith',
    'static',
    'trans',
    'blocktrans',
    'endblocktrans',
    'get_static_prefix',
    'get_media_prefix',
    'plural',
    'get_current_language',
    'language',
    'get_available_languages',
    'get_current_language_bidi',
    'get_language_info',
    'get_language_info_list',
    'localize',
    'endlocalize',
    'localtime',
    'endlocaltime',
    'timezone',
    'endtimezone',
    'get_current_timezone',
    'verbatim',
]

class name0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword)]
name0.__name__ = 'name'

class name1:
    default_text = DELIMITER
    delimited_ranges = [('name', RE(r"\w+"), [RE(r"\B|\b")], name0)]
name1.__name__ = 'name'

keyword0 = ['in', 'by', 'as']

keyword1 = [
    'truncatewords',
    'removetags',
    'linebreaksbr',
    'yesno',
    'get_digit',
    'timesince',
    'random',
    'striptags',
    'filesizeformat',
    'escape',
    'linebreaks',
    'length_is',
    'ljust',
    'rjust',
    'cut',
    'urlize',
    'fix_ampersands',
    'title',
    'floatformat',
    'capfirst',
    'pprint',
    'divisibleby',
    'add',
    'make_list',
    'unordered_list',
    'urlencode',
    'timeuntil',
    'urlizetrunc',
    'wordcount',
    'stringformat',
    'linenumbers',
    'slice',
    'date',
    'dictsort',
    'dictsortreversed',
    'default_if_none',
    'pluralize',
    'lower',
    'join',
    'center',
    'default',
    'truncatewords_html',
    'upper',
    'length',
    'phone2numeric',
    'wordwrap',
    'time',
    'addslashes',
    'slugify',
    'first',
    'escapejs',
    'force_escape',
    'iriencode',
    'last',
    'safe',
    'safeseq',
    'truncatechars',
    'localize',
    'unlocalize',
    'localtime',
    'utc',
    'timezone',
]

class _group3:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1)]
    delimited_ranges = [
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"'"), [RE(r"'")]),
    ]

class _group2:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0)]
    delimited_ranges = [('_group3', RE(r"\|[A-Za-z]+:?"), [RE(r"\B|\b")], _group3)]

class template_tag:
    default_text = DELIMITER
    delimited_ranges = [('name', name1, [RE(r"(?=%})")], _group2)]
template_tag.__name__ = 'template-tag'

class _group6:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1)]
    delimited_ranges = [
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"'"), [RE(r"'")]),
    ]

class template_variable:
    default_text = DELIMITER
    delimited_ranges = [('_group6', RE(r"\|[A-Za-z]+:?"), [RE(r"\B|\b")], _group6)]
template_variable.__name__ = 'template-variable'

word_groups = []

delimited_ranges = [
    ('comment', RE(r"\{%\s*comment\s*%}"), [RE(r"\{%\s*endcomment\s*%}")], comment),
    ('comment', RE(r"\{#"), [RE(r"#}")], comment),
    ('template-tag', RE(r"\{%"), [RE(r"%}")], template_tag),
    ('template-variable', RE(r"\{\{"), [RE(r"}}")], template_variable),
]
