# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: dockerfile.js
name = 'Dockerfile'
file_patterns = ['*.dockerfile', '*.docker']

flags = re.IGNORECASE | re.MULTILINE

keyword = """
    from maintainer cmd expose add copy entrypoint volume user workdir
    onbuild run env label
    """.split()

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

comment0 = ('comment', RE(r"#"), [RE(r"$")], comment)

keyword1 = """
    run cmd entrypoint volume add copy workdir onbuild label
    """.split()

class _group1:
    default_text_color = DELIMITER
    rules = [('keyword', keyword1)]

class _group11:
    default_text_color = DELIMITER
    rules = [
        ('_group1', RE(r"^ *(?:onbuild +)?(?:run|cmd|entrypoint|volume|add|copy|workdir|label) +"), [RE(r"\B|\b")], _group1),
    ]
_group11.__name__ = '_group1'

operator_escape = ('operator.escape', [RE(r"\\[\s\S]")])

class string:
    default_text_color = DELIMITER
    rules = [operator_escape]

class _group3:
    default_text_color = DELIMITER
    rules = [
        ('keyword', ['from', 'maintainer', 'expose', 'env', 'user', 'onbuild']),
        ('string', RE(r"'"), [RE(r"'")], string),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('number', [RE(r"\b\d+(?:\.\d+)?")]),
        comment0,
    ]

rules = [
    ('keyword', keyword),
    comment0,
    ('_group1', _group11, [RE(r"[^\\]\n")], 'bash'),
    ('_group3', RE(r"^ *(?:onbuild +)?(?:from|maintainer|expose|env|user|onbuild) +"), [RE(r"[^\\]\n")], _group3),
]
