# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: dos.js
name = 'DOS .bat'
file_patterns = ['*.dos', '*.bat', '*.cmd']

flags = re.IGNORECASE | re.MULTILINE

keyword = [
    'if',
    'else',
    'goto',
    'for',
    'in',
    'do',
    'call',
    'exit',
    'not',
    'exist',
    'errorlevel',
    'defined',
    'equ',
    'neq',
    'lss',
    'leq',
    'gtr',
    'geq',
]

built_in = [
    'prn',
    'nul',
    'lpt3',
    'lpt2',
    'lpt1',
    'con',
    'com4',
    'com3',
    'com2',
    'com1',
    'aux',
    'shift',
    'cd',
    'dir',
    'echo',
    'setlocal',
    'endlocal',
    'set',
    'pause',
    'copy',
    'append',
    'assoc',
    'at',
    'attrib',
    'break',
    'cacls',
    'cd',
    'chcp',
    'chdir',
    'chkdsk',
    'chkntfs',
    'cls',
    'cmd',
    'color',
    'comp',
    'compact',
    'convert',
    'date',
    'dir',
    'diskcomp',
    'diskcopy',
    'doskey',
    'erase',
    'fs',
    'find',
    'findstr',
    'format',
    'ftype',
    'graftabl',
    'help',
    'keyb',
    'label',
    'md',
    'mkdir',
    'mode',
    'more',
    'move',
    'path',
    'pause',
    'print',
    'popd',
    'pushd',
    'promt',
    'rd',
    'recover',
    'rem',
    'rename',
    'replace',
    'restore',
    'rmdir',
    'shiftsort',
    'start',
    'subst',
    'time',
    'title',
    'tree',
    'type',
    'ver',
    'verify',
    'vol',
    'ping',
    'net',
    'ipconfig',
    'taskkill',
    'xcopy',
    'ren',
    'del',
]

variable = [RE(r"%[^ ]|%[^ ]+?%|![^ ]+?!")]

title = [RE(r"([_a-zA-Z]\w*\.)*([_a-zA-Z]\w*:)?[_a-zA-Z]\w*")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

class function:
    default_text = DELIMITER
    word_groups = [('title', title)]
    delimited_ranges = [('comment', RE(r"@?rem\b"), [RE(r"$")], comment)]

number = [RE(r"\b\d+")]

word_groups = [
    ('keyword', keyword),
    ('built_in', built_in),
    ('variable', variable),
    ('number', number),
]

delimited_ranges = [
    ('function', RE(r"^\s*[A-Za-z._?][A-Za-z0-9_$#@~.?]*(:|\s+label)"), [RE(r"goto:eof")], function),
    ('comment', RE(r"@?rem\b"), [RE(r"$")], comment),
]
