# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: dust.js
name = 'Dust'
file_patterns = ['*.dust', '*.dst']

flags = re.IGNORECASE | re.MULTILINE

name0 = [RE(r"[a-zA-Z\.-]+")]

class template_tag:
    default_text = DELIMITER
    word_groups = [('name', name0)]
template_tag.__name__ = 'template-tag'

keyword = [
    'if',
    'eq',
    'ne',
    'lt',
    'lte',
    'gt',
    'gte',
    'select',
    'default',
    'math',
    'sep',
]

class template_variable:
    default_text = DELIMITER
    word_groups = [('keyword', keyword)]
template_variable.__name__ = 'template-variable'

word_groups = []

delimited_ranges = [
    ('template-tag', RE(r"\{[#\/]"), [RE(r"\}")], template_tag),
    ('template-variable', RE(r"\{"), [RE(r"\}")], template_variable),
]
