# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: elm.js
name = 'Elm'
file_patterns = ['*.elm']

keyword = [
    'let',
    'in',
    'if',
    'then',
    'else',
    'case',
    'of',
    'where',
    'module',
    'import',
    'exposing',
    'type',
    'alias',
    'as',
    'infix',
    'infixl',
    'infixr',
    'port',
]

keyword0 = ['module', 'where']

type = [RE(r"\b[A-Z][\w]*(\((\.\.|,|\w+)\))?")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

class _group1:
    default_text = DELIMITER
    word_groups = [('type', type)]
    delimited_ranges = [
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

class _group0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0)]
    delimited_ranges = [
        ('_group1', RE(r"\("), [RE(r"\)")], _group1),
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

keyword1 = ['import', 'as', 'exposing']

class _group7:
    default_text = DELIMITER
    word_groups = [('type', type)]
    delimited_ranges = [
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

class _group6:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1)]
    delimited_ranges = [
        ('_group7', RE(r"\("), [RE(r"\)")], _group7),
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

keyword2 = ['type', 'alias']

type0 = [RE(r"\b[A-Z][\w']*")]

class _group13:
    default_text = DELIMITER
    word_groups = [('type', type)]
    delimited_ranges = [
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

class _group16:
    default_text = DELIMITER
    word_groups = [('type', type)]
    delimited_ranges = [
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

class _group12:
    default_text = DELIMITER
    word_groups = [('keyword', keyword2), ('type', type0)]
    delimited_ranges = [
        ('_group13', RE(r"\("), [RE(r"\)")], _group13),
        ('_group16', RE(r"{"), [RE(r"}")], _group16),
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

keyword3 = ['infix', 'infixl', 'infixr']

number = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

class _group21:
    default_text = DELIMITER
    word_groups = [('keyword', keyword3), ('number', number)]
    delimited_ranges = [
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

keyword4 = ['port']

class _group24:
    default_text = DELIMITER
    word_groups = [('keyword', keyword4)]
    delimited_ranges = [
        ('comment', RE(r"--"), [RE(r"$")], comment),
        ('comment', RE(r"{-"), [RE(r"-}")], comment),
    ]

title = [RE(r"^[_a-z][\w']*")]

word_groups = [
    ('keyword', keyword),
    ('number', number),
    ('type', type0),
    ('title', title),
]

delimited_ranges = [
    ('_group0', RE(r"\b(module)"), [RE(r"where")], _group0),
    ('_group6', RE(r"import"), [RE(r"$")], _group6),
    ('_group12', RE(r"type"), [RE(r"$")], _group12),
    ('_group21', RE(r"\b(infix|infixl|infixr)"), [RE(r"$")], _group21),
    ('_group24', RE(r"port"), [RE(r"$")], _group24),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('comment', RE(r"--"), [RE(r"$")], comment),
    ('comment', RE(r"{-"), [RE(r"-}")], comment),
]
