# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: erb.js
name = 'ERB (Embedded Ruby)'
file_patterns = ['*.erb']

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

rules = [
    ('comment', RE(r"<%#"), [RE(r"%>")], comment),
    ('_group0', RE(r"<%[%=-]?"), [RE(r"[%-]?%>")], 'ruby'),
]
