# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: erlang-repl.js
name = 'Erlang REPL'
file_patterns = ['*.erlang-repl']

keyword = [
    'after',
    'and',
    'andalso',
    'band',
    'begin',
    'bnot',
    'bor',
    'bsl',
    'bsr',
    'bxor',
    'case',
    'catch',
    'cond',
    'div',
    'end',
    'fun',
    'if',
    'let',
    'not',
    'of',
    'or',
    'orelse',
    'query',
    'receive',
    'rem',
    'try',
    'when',
    'xor',
]

built_in = ['spawn', 'spawn_link', 'self']

meta = [RE(r"^[0-9]+> ")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

number = [RE(r"\b(\d+#[a-fA-F0-9]+|\d+(\.\d+)?([eE][-+]?\d+)?)")]

word_groups = [
    ('keyword', keyword),
    ('built_in', built_in),
    ('meta', meta),
    ('number', number),
]

delimited_ranges = [
    ('comment', RE(r"%"), [RE(r"$")], comment),
    ('string', RE(r"'"), [RE(r"'")]),
    ('string', RE(r"\""), [RE(r"\"")]),
]
