# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: fix.js
name = 'FIX'
file_patterns = ['*.fix']

flags = re.IGNORECASE | re.MULTILINE

class _string0:
    default_text_color = DELIMITER
    rules = [('_string', [RE(r"=")])]
_string0.__name__ = '_string'

class _string2:
    default_text_color = DELIMITER
    rules = [('_string', [RE(r"(?:[\u2401\u0001])")])]
_string2.__name__ = '_string'

class _group0:
    default_text_color = DELIMITER
    rules = [
        ('attr', RE(r"(?:[^\u2401\u0001=]+)"), [RE(r"(?==(?:[^\u2401\u0001=]+))")]),
        ('string', _string0, [_string2]),
    ]

rules = [
    ('_group0', RE(r"(?=[^\u2401\u0001]+)"), [RE(r"[\u2401\u0001]")], _group0),
]
