# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: golo.js
name = 'Golo'
file_patterns = ['*.golo']

literal = ['true', 'false', 'null']

keyword = [
    'println',
    'readln',
    'print',
    'import',
    'module',
    'function',
    'local',
    'return',
    'let',
    'var',
    'while',
    'for',
    'foreach',
    'times',
    'in',
    'case',
    'when',
    'match',
    'with',
    'break',
    'continue',
    'augment',
    'augmentation',
    'each',
    'find',
    'filter',
    'reduce',
    'if',
    'then',
    'else',
    'otherwise',
    'try',
    'catch',
    'finally',
    'raise',
    'throw',
    'orIfNull',
    'DynamicObject',
    'DynamicVariable',
    'struct',
    'Observable',
    'map',
    'set',
    'vector',
    'list',
    'array',
]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

number = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

meta = [RE(r"@[A-Za-z]+")]

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('number', number),
    ('meta', meta),
]

delimited_ranges = [
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('string', RE(r"\""), [RE(r"\"")]),
]
