# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: groovy.js
name = 'Groovy'
file_patterns = ['*.groovy']

literal = ['true', 'false', 'null']

keyword = [
    'byte',
    'short',
    'char',
    'int',
    'long',
    'boolean',
    'float',
    'double',
    'void',
    'def',
    'as',
    'in',
    'assert',
    'trait',
    'super',
    'this',
    'abstract',
    'static',
    'volatile',
    'transient',
    'public',
    'private',
    'protected',
    'synchronized',
    'final',
    'class',
    'interface',
    'enum',
    'if',
    'else',
    'for',
    'while',
    'switch',
    'case',
    'break',
    'default',
    'continue',
    'throw',
    'throws',
    'try',
    'catch',
    'finally',
    'implements',
    'extends',
    'new',
    'import',
    'package',
    'return',
    'instanceof',
]

doctag = [RE(r"@[A-Za-z]+")]

doctag0 = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag), ('doctag', doctag0)]

class comment0:
    default_text = DELIMITER
    word_groups = [('doctag', doctag0)]
comment0.__name__ = 'comment'

number = [RE(r"\b(0b[01]+)")]

keyword0 = ['class', 'interface', 'trait', 'enum']

title = [RE(r"[a-zA-Z_]\w*")]

class class0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('title', title)]
    delimited_ranges = [('_group7', RE(r"\b(extends|implements)"), [RE(r"\B|\b")])]
class0.__name__ = 'class'

number0 = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

string = [RE(r"[^\?]{0}[A-Za-z0-9_$]+ *:")]

symbol = [RE(r"^\s*[A-Za-z0-9_$]+:")]

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('number', number),
    ('number', number0),
    ('meta', doctag),
    ('string', string),
    ('symbol', symbol),
]

delimited_ranges = [
    ('comment', RE(r"/\*\*"), [RE(r"\*/")], comment),
    ('comment', RE(r"//"), [RE(r"$")], comment0),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment0),
    ('string', RE(r"\"\"\""), [RE(r"\"\"\"")]),
    ('string', RE(r"'''"), [RE(r"'''")]),
    ('string', RE(r"\$/"), [RE(r"/\$")]),
    ('string', RE(r"'"), [RE(r"'")]),
    ('regexp', RE(r"~?\/[^\/\n]+\/"), [RE(r"\B|\b")]),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('meta', RE(r"^#!/usr/bin/env"), [RE(r"$")]),
    ('class', RE(r"\b(class|interface|trait|enum)"), [RE(r"{")], class0),
    ('_group8', RE(r"\?"), [RE(r"\:")]),
]
