# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: http.js
name = 'HTTP'
file_patterns = ['*.http', '*.https']

number = [RE(r"\b\d{3}\b")]

class _group0:
    default_text = DELIMITER
    word_groups = [('number', number)]

keyword = [RE(r"[A-Z]+")]

class _group1:
    default_text = DELIMITER
    word_groups = [('keyword', keyword)]
    delimited_ranges = [('string', RE(r" "), [RE(r"(?= )")])]

class attribute:
    default_text = DELIMITER
    delimited_ranges = [('attribute', RE(r"^\w"), [RE(r"(?=: )")])]

class _group3:
    default_text = DELIMITER

word_groups = []

delimited_ranges = [
    ('_group0', RE(r"^HTTP/[0-9\.]+"), [RE(r"$")], _group0),
    ('_group1', RE(r"(?=^[A-Z]+ (.*?) HTTP/[0-9\.]+$)"), [RE(r"$")], _group1),
    ('attribute', attribute, [RE(r"(?=\B|\b)")], _group3),
]
