# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: lasso.js
name = 'Lasso'
file_patterns = ['*.lasso', '*.ls', '*.lassoscript']

flags = re.IGNORECASE | re.MULTILINE

built_in = """
    array date decimal duration integer map pair string tag xml null
    boolean bytes keyword list locale queue set stack staticarray local
    var variable global data self inherited currentcapture givenblock
    """.split()

keyword = """
    error_code error_msg error_pop error_push error_reset cache
    database_names database_schemanames database_tablenames define_tag
    define_type email_batch encode_set html_comment handle handle_error
    header if inline iterate ljax_target link link_currentaction
    link_currentgroup link_currentrecord link_detail link_firstgroup
    link_firstrecord link_lastgroup link_lastrecord link_nextgroup
    link_nextrecord link_prevgroup link_prevrecord log loop
    namespace_using output_none portal private protect records referer
    referrer repeating resultset rows search_args search_arguments
    select sort_args sort_arguments thread_atomic value_list while abort
    case else if_empty if_false if_null if_true loop_abort loop_continue
    loop_count params params_up return return_value run_children
    soap_definetag soap_lastrequest soap_lastresponse tag_name ascending
    average by define descending do equals frozen group handle_failure
    import in into join let match max min on order parent protected
    provide public require returnhome skip split_thread sum take thread
    to trait type where with yield yieldhome and or not
    """.split()

literal = """
    true false none minimal full all void bw nbw ew new cn ncn lt lte gt
    gte eq neq rx nrx ft
    """.split()

meta = [RE(r"\[/noprocess|<\?(?:lasso(?:script)?|=)")]

meta0 = [RE(r"\[")]

meta1 = [RE(r"^#!.+lasso9\b")]

class meta2:
    default_text_color = DELIMITER
    rules = [('meta', RE(r"\]|\?>"), [RE(r"\B|\b")])]
meta2.__name__ = 'meta'

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

class _group0:
    default_text_color = DELIMITER
    rules = [('comment', RE(r"<!--"), [RE(r"-->")], comment)]

class meta3:
    default_text_color = DELIMITER
    rules = [('meta', RE(r"\[noprocess\]"), [RE(r"\B|\b")])]
meta3.__name__ = 'meta'

class _group1:
    default_text_color = DELIMITER
    rules = [_group0.rules[0]]

class meta4:
    default_text_color = DELIMITER
    rules = [('meta', RE(r"\[no_square_brackets"), [RE(r"\B|\b")])]
meta4.__name__ = 'meta'

number = [
    RE(r"(?:\b0[xX][a-fA-F0-9]+|(?:\b\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)|(?:infinity|nan)\b"),
]

attr = [RE(r"-(?!infinity)[a-zA-Z_]\w*")]

attr0 = [RE(r"(?:\.\.\.)")]

class _group6:
    default_text_color = DELIMITER
    rules = [_group0.rules[0]]

class string:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '\\\\[\\s\\S]', 'relevance': 0},
    ]

symbol = [RE(r"'[a-zA-Z_][a-zA-Z0-9_.]*'")]

class _group5:
    default_text_color = DELIMITER
    rules = [('symbol', symbol)]

keyword0 = ['define']

title = [RE(r"[a-zA-Z_]\w*(?:=(?!>))?")]

class class0:
    default_text_color = DELIMITER
    rules = [('keyword', keyword0), ('title', title)]
class0.__name__ = 'class'

class _group2:
    default_text_color = DELIMITER
    rules = [
        ('built_in', built_in),
        ('keyword', keyword),
        ('literal', literal),
        ('meta', meta2, [RE(r"(?=\[noprocess\]|<\?(?:lasso(?:script)?|=))")], _group6),
        None,  # rules[4],
        ('meta', meta),
        ('comment', RE(r"/\*\*!"), [RE(r"\*/")], comment),
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('number', number),
        ('string', RE(r"'"), [RE(r"'")], string),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"`"), [RE(r"`")]),
        # ignore {'begin': '[#$][a-zA-Z_][a-zA-Z0-9_.]*'},
        ('_group4', RE(r"#"), [RE(r"\d+")]),
        ('type', RE(r"::\s*"), [RE(r"[a-zA-Z_][a-zA-Z0-9_.]*")]),
        ('attr', attr),
        ('attr', attr0),
        ('_group5', RE(r"(?:->|\.\.?)\s*"), [RE(r"\B\b")], _group5),
        ('class', RE(r"\b(?:define)"), [RE(r"(?=\(|=>)")], class0),
    ]

rules = [
    ('built_in', built_in),
    ('keyword', keyword),
    ('literal', literal),
    ('meta', meta2, [RE(r"(?=\[|<\?(?:lasso(?:script)?|=))")], _group0),
    ('meta', meta3, [RE(r"(?=\[/noprocess\])")], _group1),
    ('meta', meta),
    ('meta', meta4, [RE(r"\[/no_square_brackets\]")], _group2),
    ('meta', meta0),
    ('meta', meta1),
    _group2.rules[6],
    _group2.rules[7],
    _group2.rules[8],
    ('number', number),
    _group2.rules[10],
    _group2.rules[11],
    _group2.rules[12],
    _group2.rules[14],
    _group2.rules[14],
    _group2.rules[15],
    _group2.rules[16],
    _group2.rules[17],
    _group2.rules[18],
]

_group2.rules[4] = rules[4]
