# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: less.js
name = 'Less'
file_patterns = ['*.less']

flags = re.IGNORECASE | re.MULTILINE

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

keyword = [
    RE(r"@(import|media|charset|font-face|(-[a-z]+-)?keyframes|supports|document|namespace|page|viewport|host)\b"),
]

variable = [RE(r"@[\w-]+\s*:")]

variable0 = [RE(r"@[\w-]+")]

keyword0 = ['when']

string = [RE(r"~?'.*?'")]

string0 = [RE(r"~?\".*?\"")]

number = [
    RE(r"\b\d+(\.\d+)?(%|em|ex|ch|rem|vw|vh|vmin|vmax|cm|mm|in|pt|pc|px|deg|grad|rad|turn|s|ms|Hz|kHz|dpi|dpcm|dppx)?"),
]

number0 = [RE(r"#[0-9A-Fa-f]+\b")]

variable1 = [RE(r"@@?[\w-]+")]

variable2 = [RE(r"@{[\w-]+}")]

built_in = [RE(r"~?`[^`]*?`")]

meta = [RE(r"!important")]

class _group10:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group14', RE(r"\("), [RE(r"\)")]),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class _group5:
    default_text = DELIMITER
    word_groups = [
        ('keyword', keyword0),
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('_group6', RE(r"\b(and|not)"), [RE(r"\B|\b")]),
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group10', RE(r"\("), [RE(r"\)")], _group10),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

keyword1 = [RE(r"all\b")]

selector_tag = [RE(r"([\w-]+|@{[\w-]+})%?")]

selector_id = [RE(r"#([\w-]+|@{[\w-]+})")]

selector_class = [RE(r"\.([\w-]+|@{[\w-]+})")]

selector_tag0 = [RE(r"&")]

class _group19:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group23', RE(r"\("), [RE(r"\)")]),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class attribute:
    default_text = DELIMITER
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ]

class attribute0:
    default_text = DELIMITER
    delimited_ranges = [
        ('attribute', RE(r"([\w-]+|@{[\w-]+})"), [RE(r"(?=:)")], attribute),
    ]
attribute0.__name__ = 'attribute'

class _group35:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group39', RE(r"\("), [RE(r"\)")]),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class _group31:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group35', RE(r"\("), [RE(r"\)")], _group35),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class _group24:
    default_text = DELIMITER
    word_groups = [
        ('keyword', keyword),
        ('variable', variable),
        ('variable', variable0),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group27', RE(r"(?=[\.#:&\[])"), [RE(r"(?=[;{}])")]),
        ('_group28', RE(r"(?=([\w-]+|@{[\w-]+})[^;]*{)"), [RE(r"(?={)")]),
        ('attribute', attribute0, [RE(r"(?=})")], _group31),
    ]

class _group15:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group19', RE(r"\("), [RE(r"\)")], _group19),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
        ('_group24', RE(r"{"), [RE(r"}")], _group24),
    ]

class _group2:
    default_text = DELIMITER
    word_groups = [
        ('keyword', keyword1),
        ('variable', variable2),
        ('selector-tag', selector_tag),
        ('selector-id', selector_id),
        ('selector-class', selector_class),
        ('selector-tag', selector_tag0),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group5', RE(r"\b(when)"), [RE(r"")], _group5),
        ('selector-attr', RE(r"\["), [RE(r"\]")]),
        ('_group15', RE(r"\("), [RE(r"\)")], _group15),
    ]

class _group49:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group53', RE(r"\("), [RE(r"\)")]),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class _group44:
    default_text = DELIMITER
    word_groups = [
        ('keyword', keyword0),
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('_group45', RE(r"\b(and|not)"), [RE(r"\B|\b")]),
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group49', RE(r"\("), [RE(r"\)")], _group49),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class _group58:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group62', RE(r"\("), [RE(r"\)")]),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class _group73:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group77', RE(r"\("), [RE(r"\)")]),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class _group310:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group73', RE(r"\("), [RE(r"\)")], _group73),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]
_group310.__name__ = '_group31'

class _group63:
    default_text = DELIMITER
    word_groups = [
        ('keyword', keyword),
        ('variable', variable),
        ('variable', variable0),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group66', RE(r"(?=[\.#:&\[])"), [RE(r"(?=[;{}])")]),
        ('_group67', RE(r"(?=([\w-]+|@{[\w-]+})[^;]*{)"), [RE(r"(?={)")]),
        ('attribute', attribute0, [RE(r"(?=})")], _group310),
    ]

class _group54:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group58', RE(r"\("), [RE(r"\)")], _group58),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
        ('_group63', RE(r"{"), [RE(r"}")], _group63),
    ]

class _group41:
    default_text = DELIMITER
    word_groups = [
        ('keyword', keyword1),
        ('variable', variable2),
        ('selector-tag', selector_tag),
        ('selector-id', selector_id),
        ('selector-class', selector_class),
        ('selector-tag', selector_tag0),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group44', RE(r"\b(when)"), [RE(r"")], _group44),
        ('selector-attr', RE(r"\["), [RE(r"\]")]),
        ('_group54', RE(r"\("), [RE(r"\)")], _group54),
    ]

class _group85:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group89', RE(r"\("), [RE(r"\)")]),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

class _group81:
    default_text = DELIMITER
    word_groups = [
        ('string', string),
        ('string', string0),
        ('number', number),
        ('number', number0),
        ('variable', variable1),
        ('variable', variable2),
        ('built_in', built_in),
        ('meta', meta),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('_group85', RE(r"\("), [RE(r"\)")], _group85),
        ('attribute', RE(r"(?=[\w-]+\s*:)"), [RE(r"(?=:)")]),
    ]

word_groups = [('keyword', keyword), ('variable', variable), ('variable', variable0)]

delimited_ranges = [
    ('comment', RE(r"//"), [RE(r"$")], comment),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('_group2', RE(r"(?=[\.#:&\[])"), [RE(r"(?=[;{}])")], _group2),
    ('_group41', RE(r"(?=([\w-]+|@{[\w-]+})[^;]*{)"), [RE(r"(?={)")], _group41),
    ('attribute', attribute0, [RE(r"(?=\B|\b)")], _group81),
]
