# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: livescript.js
name = 'LiveScript'
file_patterns = ['*.livescript', '*.ls']

literal = [
    'true',
    'false',
    'null',
    'undefined',
    'yes',
    'no',
    'on',
    'off',
    'it',
    'that',
    'void',
]

keyword = [
    'in',
    'if',
    'for',
    'while',
    'finally',
    'new',
    'do',
    'return',
    'else',
    'break',
    'catch',
    'instanceof',
    'throw',
    'try',
    'this',
    'switch',
    'continue',
    'typeof',
    'delete',
    'debugger',
    'case',
    'default',
    'function',
    'var',
    'with',
    'then',
    'unless',
    'until',
    'loop',
    'of',
    'by',
    'when',
    'and',
    'or',
    'is',
    'isnt',
    'not',
    'it',
    'that',
    'otherwise',
    'from',
    'to',
    'til',
    'fallthrough',
    'super',
    'case',
    'default',
    'function',
    'var',
    'void',
    'const',
    'let',
    'enum',
    'export',
    'import',
    'native',
    '__hasProp',
    '__extends',
    '__slice',
    '__bind',
    '__indexOf',
]

built_in = [
    'npm',
    'require',
    'console',
    'print',
    'module',
    'global',
    'window',
    'document',
]

number = [RE(r"\b(0b[01]+)")]

number0 = [
    RE(r"(\b0[xX][a-fA-F0-9_]+)|(\b\d(\d|_\d)*(\.(\d(\d|_\d)*)?)?(_*[eE]([-+]\d(_\d|\d)*)?)?[_a-z]*)"),
]

class subst:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
    ]

class string:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

class regexp:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst),
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]

regexp0 = [RE(r"\/(?![ *])(\\\/|.)*?\/[gim]*(?=\W|$)")]

class subst0:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp),
        ('_group8', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst0.__name__ = 'subst'

class string0:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst0),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]
string0.__name__ = 'string'

class subst1:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp),
        ('_group15', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst1.__name__ = 'subst'

class string1:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst1),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]
string1.__name__ = 'string'

class subst2:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")]),
        ('_group21', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst2.__name__ = 'subst'

class regexp1:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst2),
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]
regexp1.__name__ = 'regexp'

title = [RE(r"[A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")]

class subst3:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp),
        ('_group36', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst3.__name__ = 'subst'

class string2:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst3),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]
string2.__name__ = 'string'

class subst4:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp),
        ('_group43', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst4.__name__ = 'subst'

class string3:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst4),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]
string3.__name__ = 'string'

class subst5:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")]),
        ('_group49', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst5.__name__ = 'subst'

class regexp2:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst5),
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]
regexp2.__name__ = 'regexp'

class _group27:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string2),
        ('string', RE(r"\""), [RE(r"\"")], string3),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp2),
        ('_group52', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]

class params:
    default_text = DELIMITER
    delimited_ranges = [('_group27', RE(r"\("), [RE(r"\)")], _group27)]

class function:
    default_text = DELIMITER
    word_groups = [('title', title)]
    delimited_ranges = [('params', RE(r"(?=\()"), [RE(r"\B|\b")], params)]

class subst6:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp),
        ('_group62', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst6.__name__ = 'subst'

class string4:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst6),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]
string4.__name__ = 'string'

class subst7:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp),
        ('_group69', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst7.__name__ = 'subst'

class string5:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst7),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]
string5.__name__ = 'string'

class subst8:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")]),
        ('_group75', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst8.__name__ = 'subst'

class regexp3:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst8),
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]
regexp3.__name__ = 'regexp'

class _group53:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string4),
        ('string', RE(r"\""), [RE(r"\"")], string5),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp3),
        ('_group78', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]

class params0:
    default_text = DELIMITER
    delimited_ranges = [('_group53', RE(r"\("), [RE(r"\)")], _group53)]
params0.__name__ = 'params'

class function0:
    default_text = DELIMITER
    word_groups = [('title', title)]
    delimited_ranges = [('params', RE(r"(?=\()"), [RE(r"\B|\b")], params0)]
function0.__name__ = 'function'

class subst9:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")]),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp),
        ('_group88', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst9.__name__ = 'subst'

class string6:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst9),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]
string6.__name__ = 'string'

class subst10:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp),
        ('_group95', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst10.__name__ = 'subst'

class string7:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst10),
        ('subst', RE(r"#[A-Za-z$_]"), [RE(r"(?:\-[0-9A-Za-z$_]|[0-9A-Za-z$_])*")], subst),
    ]
string7.__name__ = 'string'

class subst11:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string),
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")]),
        ('_group101', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]
subst11.__name__ = 'subst'

class regexp4:
    default_text = DELIMITER
    delimited_ranges = [
        ('subst', RE(r"#\{"), [RE(r"}")], subst11),
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]
regexp4.__name__ = 'regexp'

class _group79:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('number', number),
        ('number', number0),
        ('regexp', regexp0),
    ]
    delimited_ranges = [
        ('string', RE(r"'''"), [RE(r"'''")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string6),
        ('string', RE(r"\""), [RE(r"\"")], string7),
        ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
        ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp4),
        ('_group104', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ]

class params1:
    default_text = DELIMITER
    delimited_ranges = [('_group79', RE(r"\("), [RE(r"\)")], _group79)]
params1.__name__ = 'params'

class function1:
    default_text = DELIMITER
    word_groups = [('title', title)]
    delimited_ranges = [('params', RE(r"(?=\()"), [RE(r"\B|\b")], params1)]
function1.__name__ = 'function'

keyword0 = ['class']

keyword1 = ['extends']

class _group105:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1), ('title', title)]

class class0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('title', title)]
    delimited_ranges = [('_group105', RE(r"\b(extends)"), [RE(r"")], _group105)]
class0.__name__ = 'class'

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('built_in', built_in),
    ('number', number),
    ('number', number0),
    ('regexp', regexp0),
]

delimited_ranges = [
    ('string', RE(r"'''"), [RE(r"'''")]),
    ('string', RE(r"'"), [RE(r"'")]),
    ('string', RE(r"\"\"\""), [RE(r"\"\"\"")], string0),
    ('string', RE(r"\""), [RE(r"\"")], string1),
    ('string', RE(r"\\"), [RE(r"(?=(\s|$))")]),
    ('regexp', RE(r"//"), [RE(r"//[gim]*")], regexp1),
    ('_group24', RE(r"``"), [RE(r"(?=``)")], 'javascript'),
    ('comment', RE(r"\/\*"), [RE(r"\*\/")], comment),
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('function', RE(r"(?=([A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*\s*(?:=|:=)\s*)?(\(.*\))?\s*\B\->\*?)"), [RE(r"\->\*?")], function),
    ('function', RE(r"(?=([A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*\s*(?:=|:=)\s*)?!?(\(.*\))?\s*\B[-~]{1,2}>\*?)"), [RE(r"[-~]{1,2}>\*?")], function0),
    ('function', RE(r"(?=([A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*\s*(?:=|:=)\s*)?(\(.*\))?\s*\B!?[-~]{1,2}>\*?)"), [RE(r"!?[-~]{1,2}>\*?")], function1),
    ('class', RE(r"\b(class)"), [RE(r"$")], class0),
    ('_group106', RE(r"(?=[A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*:)"), [RE(r"(?=:)")]),
]
