# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: makefile.js
name = 'Makefile'
file_patterns = ['*.makefile', '*.mk', '*.mak']

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

section = [RE(r"^[\w]+:\s*$")]

keyword = ['.PHONY']

class meta:
    default_text = DELIMITER
    word_groups = [('keyword', keyword)]

class _group2:
    default_text = DELIMITER
    delimited_ranges = [
        ('string', RE(r"\""), [RE(r"\"")]),
        ('variable', RE(r"\$\("), [RE(r"\)")]),
    ]

word_groups = [('section', section)]

delimited_ranges = [
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('meta', RE(r"^\.PHONY:"), [RE(r"$")], meta),
    ('_group2', RE(r"^\t+"), [RE(r"$")], _group2),
]
