# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: mojolicious.js
name = 'Mojolicious'
file_patterns = ['*.mojolicious']

meta = [RE(r"^__(END|DATA)__$")]

rules = [
    ('meta', meta),
    ('_group0', RE(r"^\s*%{1,2}={0,2}"), [RE(r"$")], 'perl'),
    ('_group1', RE(r"<%{1,2}={0,2}"), [RE(r"(?=={0,1}%>)")], 'perl'),
]

# TODO merge "word_groups" and "delimited_ranges" into "rules" in editxt.syntax
assert "__obj" not in globals()
assert "__fixup" not in globals()
def __fixup(obj):
    groups = []
    ranges = []
    rules = getattr(obj, "rules", [])
    for i, rng in reversed(list(enumerate(rules))):
        if len(rng) == 2:
            groups.append(rng)
        else:
            assert len(rng) > 2, rng
            ranges.append(rng)
    return groups, ranges

class __obj:
    rules = globals().get("rules", [])
word_groups, delimited_ranges = __fixup(__obj)

for __obj in globals().values():
    if hasattr(__obj, "rules"):
        __obj.word_groups, __obj.delimited_ranges = __fixup(__obj)

del __obj, __fixup
