# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: monkey.js
name = 'Monkey'
file_patterns = ['*.monkey']

flags = re.IGNORECASE | re.MULTILINE

literal = ['true', 'false', 'null', 'and', 'or', 'shl', 'shr', 'mod']

keyword = [
    'public',
    'private',
    'property',
    'continue',
    'exit',
    'extern',
    'new',
    'try',
    'catch',
    'eachin',
    'not',
    'abstract',
    'final',
    'select',
    'case',
    'default',
    'const',
    'local',
    'global',
    'field',
    'end',
    'if',
    'then',
    'else',
    'elseif',
    'endif',
    'while',
    'wend',
    'repeat',
    'until',
    'forever',
    'for',
    'to',
    'step',
    'next',
    'return',
    'module',
    'inline',
    'throw',
    'import',
]

built_in = [
    'DebugLog',
    'DebugStop',
    'Error',
    'Print',
    'ACos',
    'ACosr',
    'ASin',
    'ASinr',
    'ATan',
    'ATan2',
    'ATan2r',
    'ATanr',
    'Abs',
    'Abs',
    'Ceil',
    'Clamp',
    'Clamp',
    'Cos',
    'Cosr',
    'Exp',
    'Floor',
    'Log',
    'Max',
    'Max',
    'Min',
    'Min',
    'Pow',
    'Sgn',
    'Sgn',
    'Sin',
    'Sinr',
    'Sqrt',
    'Tan',
    'Tanr',
    'Seed',
    'PI',
    'HALFPI',
    'TWOPI',
]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

keyword0 = ['function', 'method']

title = [RE(r"[a-zA-Z_]\w*")]

class function:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('title', title)]

keyword1 = ['class', 'interface']

class class0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1), ('title', title)]
    delimited_ranges = [('_group2', RE(r"\b(extends|implements)"), [RE(r"\B|\b")])]
class0.__name__ = 'class'

built_in0 = [RE(r"\b(self|super)\b")]

keyword2 = ['if', 'else', 'elseif', 'endif', 'end', 'then']

class meta:
    default_text = DELIMITER
    word_groups = [('keyword', keyword2)]

meta0 = [RE(r"^\s*strict\b")]

keyword3 = ['alias']

class _group3:
    default_text = DELIMITER
    word_groups = [('keyword', keyword3), ('title', title)]

number = [RE(r"[$][a-fA-F0-9]+")]

number0 = [RE(r"\b\d+(\.\d+)?")]

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('built_in', built_in),
    ('built_in', built_in0),
    ('meta', meta0),
    ('number', number),
    ('number', number0),
]

delimited_ranges = [
    ('comment', RE(r"#rem"), [RE(r"#end")], comment),
    ('comment', RE(r"'"), [RE(r"$")], comment),
    ('function', RE(r"\b(function|method)"), [RE(r"[(=:]|$")], function),
    ('class', RE(r"\b(class|interface)"), [RE(r"$")], class0),
    ('meta', RE(r"\s*#"), [RE(r"$")], meta),
    ('_group3', RE(r"\b(alias)"), [RE(r"=")], _group3),
    ('string', RE(r"\""), [RE(r"\"")]),
]
