# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: monkey.js
name = 'Monkey'
file_patterns = ['*.monkey']

flags = re.IGNORECASE | re.MULTILINE

built_in = """
    DebugLog DebugStop Error Print ACos ACosr ASin ASinr ATan ATan2
    ATan2r ATanr Abs Abs Ceil Clamp Clamp Cos Cosr Exp Floor Log Max Max
    Min Min Pow Sgn Sgn Sin Sinr Sqrt Tan Tanr Seed PI HALFPI TWOPI
    """.split()

keyword = """
    public private property continue exit extern new try catch eachin
    not abstract final select case default const local global field end
    if then else elseif endif while wend repeat until forever for to
    step next return module inline throw import
    """.split()

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

title = ('title', [RE(r"[a-zA-Z_]\w*")])

class function:
    default_text_color = DELIMITER
    rules = [('keyword', ['function', 'method']), title]

class class0:
    default_text_color = DELIMITER
    rules = [
        ('keyword', ['class', 'interface']),
        ('_group1', RE(r"\b(?:extends|implements)"), [RE(r"\B\b")]),
        title,
    ]
class0.__name__ = 'class'

class meta:
    default_text_color = DELIMITER
    rules = [
        ('meta-keyword', ['if', 'else', 'elseif', 'endif', 'end', 'then']),
    ]

class _group2:
    default_text_color = DELIMITER
    rules = [('keyword', ['alias']), title]

class string:
    default_text_color = DELIMITER
    rules = [('operator.escape', [RE(r"\\[\s\S]")])]

rules = [
    ('built_in', built_in),
    ('keyword', keyword),
    ('literal', ['true', 'false', 'null', 'and', 'or', 'shl', 'shr', 'mod']),
    ('comment', RE(r"#rem"), [RE(r"#end")], comment),
    ('comment', RE(r"'"), [RE(r"$")], comment),
    ('function', RE(r"\b(?:function|method)"), [RE(r"[(?:=:]|$")], function),
    ('class', RE(r"\b(?:class|interface)"), [RE(r"$")], class0),
    ('built_in', [RE(r"\b(?:self|super)\b")]),
    ('meta', RE(r"\s*#"), [RE(r"$")], meta),
    ('meta', [RE(r"^\s*strict\b")]),
    ('_group2', RE(r"\b(?:alias)"), [RE(r"=")], _group2),
    ('string', RE(r"\""), [RE(r"\"")], string),
    ('number', [RE(r"[$][a-fA-F0-9]+")]),
    ('number', [RE(r"\b\d+(?:\.\d+)?")]),
]
