# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: nginx.js
name = 'Nginx'
file_patterns = ['*.nginx', '*.nginxconf']

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

comment0 = ('comment', RE(r"#"), [RE(r"$")], comment)

class _group1:
    default_text_color = DELIMITER
    rules = [('section', [RE(r"[a-zA-Z_]\w*")])]

class attribute0:
    default_text_color = DELIMITER
    rules = [('attribute', RE(r"[a-zA-Z_]\w*"), [RE(r"\B|\b")])]
attribute0.__name__ = 'attribute'

literal = """
    on off yes no true false none blocked debug info notice warn error
    crit select break last permanent redirect kqueue rtsig epoll poll
    /dev/poll
    """.split()

operator_escape = ('operator.escape', [RE(r"\\[\s\S]")])

variable = ('variable', [RE(r"\$\d+")])

variable0 = ('variable', RE(r"\$\{"), [RE(r"}")])

variable1 = ('variable', [RE(r"[\$\@][a-zA-Z_]\w*")])

class string:
    default_text_color = DELIMITER
    rules = [operator_escape, variable, variable0, variable1]

class _group4:
    default_text_color = DELIMITER
    rules = [variable, variable0, variable1]

class regexp:
    default_text_color = DELIMITER
    rules = [operator_escape, variable, variable0, variable1]

class _group3:
    default_text_color = DELIMITER
    rules = [
        ('literal', literal),
        comment0,
        ('string', RE(r"\""), [RE(r"\"")], string),
        ('string', RE(r"'"), [RE(r"'")], string),
        ('_group4', RE(r"(?:[a-z]+):/"), [RE(r"\s")], _group4),
        ('regexp', RE(r"\s\^"), [RE(r"(?=\s|{|;)")], regexp),
        ('regexp', RE(r"~\*?\s+"), [RE(r"(?=\s|{|;)")], regexp),
        ('regexp', RE(r"\*(?:\.[a-z\-]+)+"), [RE(r"\B\b")], regexp),
        ('regexp', RE(r"(?:[a-z\-]+\.)+\*"), [RE(r"\B\b")], regexp),
        ('number', [RE(r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(?::\d{1,5})?\b")]),
        ('number', [RE(r"\b\d+[kKmMgGdshdwy]*\b")]),
        variable,
        variable0,
        variable1,
    ]

class _group2:
    default_text_color = DELIMITER
    rules = [('attribute', attribute0, [RE(r"\B\b")], _group3)]

rules = [
    comment0,
    ('_group1', RE(r"(?=[a-zA-Z_]\w*\s+{)"), [RE(r"{")], _group1),
    ('_group2', RE(r"(?=[a-zA-Z_]\w*\s)"), [RE(r";|{")], _group2),
]
