# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: profile.js
name = 'Python profile'
file_patterns = ['*.profile']

number = [
    RE(r"(?:\b0[xX][a-fA-F0-9]+|(?:\b\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)"),
]

number0 = ('number', number)

class _group1:
    default_text_color = DELIMITER
    rules = [('keyword', ['ncalls', 'tottime', 'cumtime', 'filename'])]

class _group2:
    default_text_color = DELIMITER
    rules = [number0]

operator_escape = ('operator.escape', [RE(r"\\[\s\S]")])

class string:
    default_text_color = DELIMITER
    rules = [operator_escape]

class _string:
    default_text_color = DELIMITER
    rules = [('string', [RE(r"\(")])]

class _string0:
    default_text_color = DELIMITER
    rules = [('string', [RE(r"\)$")])]
_string0.__name__ = '_string'

rules = [
    number0,
    ('_group0', RE(r"[a-zA-Z_][\da-zA-Z_]+\.[\da-zA-Z_]{1,3}"), [RE(r":")]),
    ('_group1', RE(r"(?:ncalls|tottime|cumtime)"), [RE(r"$")], _group1),
    ('_group2', RE(r"function calls"), [RE(r"$")], _group2),
    ('string', RE(r"'"), [RE(r"'")], string),
    ('string', RE(r"\""), [RE(r"\"")], string),
    ('string', _string, [_string0]),
]
