# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: prolog.js
name = 'Prolog'
file_patterns = ['*.prolog']

symbol = [RE(r"[A-Z][a-zA-Z0-9_]*")]

symbol0 = [RE(r"_[A-Za-z0-9_]*")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

string = [RE(r"0\'(\\\'|.)")]

string0 = [RE(r"0\'\\s")]

number = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

class _group5:
    default_text = DELIMITER
    word_groups = [
        ('symbol', symbol),
        ('symbol', symbol0),
        ('string', string),
        ('string', string0),
        ('number', number),
    ]
    delimited_ranges = [
        ('_group7', RE(r"\("), [RE(r"\)")]),
        ('_group9', RE(r"\["), [RE(r"\]")]),
        ('comment', RE(r"%"), [RE(r"$")]),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"`"), [RE(r"`")]),
    ]

class _group1:
    default_text = DELIMITER
    word_groups = [
        ('symbol', symbol),
        ('symbol', symbol0),
        ('string', string),
        ('string', string0),
        ('number', number),
    ]
    delimited_ranges = [
        ('_group3', RE(r"\("), [RE(r"\)")]),
        ('_group5', RE(r"\["), [RE(r"\]")], _group5),
        ('comment', RE(r"%"), [RE(r"$")]),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"`"), [RE(r"`")]),
    ]

class _group23:
    default_text = DELIMITER
    word_groups = [
        ('symbol', symbol),
        ('symbol', symbol0),
        ('string', string),
        ('string', string0),
        ('number', number),
    ]
    delimited_ranges = [
        ('_group25', RE(r"\("), [RE(r"\)")]),
        ('_group27', RE(r"\["), [RE(r"\]")]),
        ('comment', RE(r"%"), [RE(r"$")]),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"`"), [RE(r"`")]),
    ]

class _group21:
    default_text = DELIMITER
    word_groups = [
        ('symbol', symbol),
        ('symbol', symbol0),
        ('string', string),
        ('string', string0),
        ('number', number),
    ]
    delimited_ranges = [
        ('_group23', RE(r"\("), [RE(r"\)")], _group23),
        ('_group34', RE(r"\["), [RE(r"\]")]),
        ('comment', RE(r"%"), [RE(r"$")]),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('string', RE(r"\""), [RE(r"\"")]),
        ('string', RE(r"'"), [RE(r"'")]),
        ('string', RE(r"`"), [RE(r"`")]),
    ]

word_groups = [
    ('symbol', symbol),
    ('symbol', symbol0),
    ('string', string),
    ('string', string0),
    ('number', number),
]

delimited_ranges = [
    ('_group1', RE(r"\("), [RE(r"\)")], _group1),
    ('_group21', RE(r"\["), [RE(r"\]")], _group21),
    ('comment', RE(r"%"), [RE(r"$")]),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('string', RE(r"'"), [RE(r"'")]),
    ('string', RE(r"`"), [RE(r"`")]),
]
