# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: roboconf.js
name = 'Roboconf'
file_patterns = ['*.roboconf', '*.graph', '*.instances']

flags = re.IGNORECASE | re.MULTILINE

keyword = ['import']

keyword0 = ['facet']

class attribute:
    default_text = DELIMITER
    delimited_ranges = [('attribute', RE(r"[a-zA-Z-_]+"), [RE(r"(?=\s*:)")])]

variable = [RE(r"\.[a-zA-Z-_]+")]

keyword1 = [RE(r"\(optional\)")]

class _group1:
    default_text = DELIMITER
    word_groups = [('variable', variable), ('keyword', keyword1)]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

class _group0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0)]
    delimited_ranges = [
        ('attribute', attribute, [RE(r"(?=})")], _group1),
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]

keyword2 = [
    'name',
    'count',
    'channels',
    'instance-data',
    'instance-state',
    'instance',
    'of',
]

class _group4:
    default_text = DELIMITER
    word_groups = [('variable', variable), ('keyword', keyword1)]

class _group3:
    default_text = DELIMITER
    word_groups = [('keyword', keyword2)]
    delimited_ranges = [
        ('attribute', attribute, [RE(r"(?=})")], _group4),
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]

class _group7:
    default_text = DELIMITER
    word_groups = [('variable', variable), ('keyword', keyword1)]

class _group6:
    default_text = DELIMITER
    delimited_ranges = [
        ('attribute', attribute, [RE(r"(?=})")], _group7),
        ('comment', RE(r"#"), [RE(r"$")], comment),
    ]

word_groups = [('keyword', keyword)]

delimited_ranges = [
    ('_group0', RE(r"^facet [a-zA-Z-_][^\n{]+\{"), [RE(r"}")], _group0),
    ('_group3', RE(r"^\s*instance of [a-zA-Z-_][^\n{]+\{"), [RE(r"}")], _group3),
    ('_group6', RE(r"^[a-zA-Z-_][^\n{]+\{"), [RE(r"}")], _group6),
    ('comment', RE(r"#"), [RE(r"$")], comment),
]
