# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: scala.js
name = 'Scala'
file_patterns = ['*.scala']

keyword = """
    type yield lazy override def with val var sealed abstract private
    trait object if forSome for while throw finally protected extends
    import final return else break new catch super class case package
    default try this match continue throws implicit
    """.split()

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

operator_escape = ('operator.escape', [RE(r"\\[\s\S]")])

class string:
    default_text_color = DELIMITER
    rules = [operator_escape]

subst = ('subst', [RE(r"\$[A-Za-z0-9_]+")])

subst0 = ('subst', RE(r"\${"), [RE(r"}")])

class string2:
    default_text_color = DELIMITER
    rules = [operator_escape, subst, subst0]
string2.__name__ = 'string'

class string4:
    default_text_color = DELIMITER
    rules = [subst, subst0]
string4.__name__ = 'string'

title = [
    RE(r"[^0-9\n\t \"'(?:),.`{}\[\]:;][^\n\t \"'(?:),.`{}\[\]:;]+|[^0-9\n\t \"'(?:),.`{}\[\]:;=]"),
]

title0 = ('title', title)

class function:
    default_text_color = DELIMITER
    rules = [('keyword', ['def']), title0]

class _class0:
    default_text_color = DELIMITER
    rules = [('_class', [RE(r"[:={\[\n;]")])]
_class0.__name__ = '_class'

class class0:
    default_text_color = DELIMITER
    rules = [
        ('keyword', ['class', 'object', 'trait', 'type']),
        ('_group1', RE(r"\b(?:extends|with)"), [RE(r"\B\b")]),
        ('params', RE(r"\("), [RE(r"\)")]),
        title0,
    ]
class0.__name__ = 'class'

number = [
    RE(r"(?:\b0[xX][a-fA-F0-9]+|(?:\b\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)"),
]

rules = [
    ('keyword', keyword),
    ('literal', ['true', 'false', 'null']),
    ('comment', RE(r"//"), [RE(r"$")], comment),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('string', RE(r"\""), [RE(r"\"")], string),
    ('string', RE(r"\"\"\""), [RE(r"\"\"\"")]),
    ('string', RE(r"[a-z]+\""), [RE(r"\"")], string2),
    ('string', RE(r"[a-z]+\"\"\""), [RE(r"\"\"\"")], string4),
    ('symbol', [RE(r"'\w[\w\d_]*(?!')")]),
    ('type', [RE(r"\b[A-Z][A-Za-z0-9_]*")]),
    ('function', RE(r"\b(?:def)"), [RE(r"[:={\[(?:\n;]")], function),
    ('class', RE(r"\b(?:class|object|trait|type)"), [_class0], class0),
    ('number', number),
    ('meta', [RE(r"@[A-Za-z]+")]),
]
