# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: smalltalk.js
name = 'Smalltalk'
file_patterns = ['*.smalltalk', '*.st']

keyword = ['self', 'super', 'nil', 'true', 'false', 'thisContext']

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

class string:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '\\\\[\\s\\S]', 'relevance': 0},
    ]

type = [RE(r"\b[A-Z][A-Za-z0-9_]*")]

number = [
    RE(r"(?:\b0[xX][a-fA-F0-9]+|(?:\b\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)"),
]

symbol = [RE(r"#[a-zA-Z_]\w*")]

string0 = [RE(r"\$.{1}")]

class _group0:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '(\\|[ ]*)?[a-z][a-zA-Z0-9_]*'},
    ]

class _group1:
    default_text_color = DELIMITER
    rules = [
        None,  # rules[2],
        ('string', string0),
        ('number', number),
        ('symbol', symbol),
    ]

rules = [
    ('keyword', keyword),
    ('comment', RE(r"\""), [RE(r"\"")], comment),
    ('string', RE(r"'"), [RE(r"'")], string),
    ('type', type),
    # ignore {'begin': '[a-z][a-zA-Z0-9_]*:', 'relevance': 0},
    ('number', number),
    ('symbol', symbol),
    ('string', string0),
    ('_group0', RE(r"(?=\|[ ]*[a-z][a-zA-Z0-9_]*(?:[ ]+[a-z][a-zA-Z0-9_]*)*[ ]*\|)"), [RE(r"\|")], _group0),
    ('_group1', RE(r"\#\("), [RE(r"\)")], _group1),
]

_group1.rules[0] = rules[2]
