# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: sml.js
name = 'SML'
file_patterns = ['*.sml', '*.ml']

built_in = [
    'array',
    'bool',
    'char',
    'exn',
    'int',
    'list',
    'option',
    'order',
    'real',
    'ref',
    'string',
    'substring',
    'vector',
    'unit',
    'word',
]

keyword = [
    'abstype',
    'and',
    'andalso',
    'as',
    'case',
    'datatype',
    'do',
    'else',
    'end',
    'eqtype',
    'exception',
    'fn',
    'fun',
    'functor',
    'handle',
    'if',
    'in',
    'include',
    'infix',
    'infixr',
    'let',
    'local',
    'nonfix',
    'of',
    'op',
    'open',
    'orelse',
    'raise',
    'rec',
    'sharing',
    'sig',
    'signature',
    'struct',
    'structure',
    'then',
    'type',
    'val',
    'with',
    'withtype',
    'where',
    'while',
]

literal = ['true', 'false', 'NONE', 'SOME', 'LESS', 'EQUAL', 'GREATER', 'nil']

literal0 = [RE(r"\[(\|\|)?\]|\(\)")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    rules = [('doctag', doctag)]

symbol = [RE(r"'[A-Za-z_](?!')[\w']*")]

type = [RE(r"`[A-Z][\w']*")]

type0 = [RE(r"\b[A-Z][\w']*")]

class string:
    default_text = DELIMITER
    rules = [
        # {'begin': '\\\\[\\s\\S]', 'relevance': 0},
    ]

number = [
    RE(r"\b(0[xX][a-fA-F0-9_]+[Lln]?|0[oO][0-7_]+[Lln]?|0[bB][01_]+[Lln]?|[0-9][0-9_]*([Lln]|(\.[0-9_]*)?([eE][-+]?[0-9_]+)?)?)"),
]

rules = [
    ('built_in', built_in),
    ('keyword', keyword),
    ('literal', literal),
    ('literal', literal0),
    ('comment', RE(r"\(\*"), [RE(r"\*\)")], comment),
    ('symbol', symbol),
    ('type', type),
    ('type', type0),
    ('string', RE(r"'"), [RE(r"'")]),
    ('string', RE(r"\""), [RE(r"\"")], string),
    ('number', number),
]

# TODO merge "word_groups" and "delimited_ranges" into "rules" in editxt.syntax
assert "__obj" not in globals()
assert "__fixup" not in globals()
def __fixup(obj):
    groups = []
    ranges = []
    rules = getattr(obj, "rules", [])
    for i, rng in reversed(list(enumerate(rules))):
        if len(rng) == 2:
            groups.append(rng)
        else:
            assert len(rng) > 2, rng
            ranges.append(rng)
    return groups, ranges

class __obj:
    rules = globals().get("rules", [])
word_groups, delimited_ranges = __fixup(__obj)

for __obj in globals().values():
    if hasattr(__obj, "rules"):
        __obj.word_groups, __obj.delimited_ranges = __fixup(__obj)

del __obj, __fixup
