# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: step21.js
name = 'STEP Part 21 (ISO 10303-21)'
file_patterns = ['*.step21', '*.p21', '*.step', '*.stp']

flags = re.IGNORECASE | re.MULTILINE

keyword = ['HEADER', 'ENDSEC', 'DATA']

meta = [RE(r"ISO-10303-21;")]

meta0 = [RE(r"END-ISO-10303-21;")]

number = [
    RE(r"(?:\b0[xX][a-fA-F0-9]+|(?:\b\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)"),
]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

class string:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '\\\\[\\s\\S]', 'relevance': 0},
    ]

rules = [
    ('keyword', keyword),
    ('meta', meta),
    ('meta', meta0),
    ('comment', RE(r"//"), [RE(r"$")], comment),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('comment', RE(r"/\*\*!"), [RE(r"\*/")], comment),
    ('number', number),
    ('string', RE(r"'"), [RE(r"'")], string),
    ('string', RE(r"\""), [RE(r"\"")], string),
    ('string', RE(r"'"), [RE(r"'")]),
    ('symbol', RE(r"#"), [RE(r"\d+")]),
]
