# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: tex.js
name = 'TeX'
file_patterns = ['*.tex']

class name1:
    default_text_color = DELIMITER
    rules = [('name', RE(r"[a-zA-Zа-яА-я]+[*]?"), [RE(r"\B|\b")])]
name1.__name__ = 'name'

class _group1:
    default_text_color = DELIMITER
    rules = [('number', [RE(r"-?\d*\.?\d+(?:pt|pc|mm|cm|in|dd|cc|ex|em)?")])]

class _group0:
    default_text_color = DELIMITER
    rules = [
        ('string', RE(r"\["), [RE(r"\]")]),
        ('string', RE(r"\{"), [RE(r"\}")]),
        ('_group1', RE(r"\s*=\s*"), [RE(r"\B\b")], _group1),
    ]

class name4:
    default_text_color = DELIMITER
    rules = [('name', RE(r"[^a-zA-Zа-яА-я0-9]"), [RE(r"\B|\b")])]
name4.__name__ = 'name'

class tag:
    default_text_color = DELIMITER
    rules = [
        ('name', name1, [RE(r"\B\b")], _group0),
        ('name', name4, [RE(r"\B\b")], _group0),
    ]

tag0 = ('tag', RE(r"\\"), [RE(r"\B\b")], tag)

class formula:
    default_text_color = DELIMITER
    rules = [tag0]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

rules = [
    tag0,
    ('formula', RE(r"\$\$"), [RE(r"\$\$")], formula),
    ('formula', RE(r"\$"), [RE(r"\$")], formula),
    ('comment', RE(r"%"), [RE(r"$")], comment),
]
