# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: tp.js
name = 'TP'
file_patterns = ['*.tp']

literal = [
    'ON',
    'OFF',
    'max_speed',
    'LPOS',
    'JPOS',
    'ENABLE',
    'DISABLE',
    'START',
    'STOP',
    'RESET',
]

keyword = [
    'ABORT',
    'ACC',
    'ADJUST',
    'AND',
    'AP_LD',
    'BREAK',
    'CALL',
    'CNT',
    'COL',
    'CONDITION',
    'CONFIG',
    'DA',
    'DB',
    'DIV',
    'DETECT',
    'ELSE',
    'END',
    'ENDFOR',
    'ERR_NUM',
    'ERROR_PROG',
    'FINE',
    'FOR',
    'GP',
    'GUARD',
    'INC',
    'IF',
    'JMP',
    'LINEAR_MAX_SPEED',
    'LOCK',
    'MOD',
    'MONITOR',
    'OFFSET',
    'Offset',
    'OR',
    'OVERRIDE',
    'PAUSE',
    'PREG',
    'PTH',
    'RT_LD',
    'RUN',
    'SELECT',
    'SKIP',
    'Skip',
    'TA',
    'TB',
    'TO',
    'TOOL_OFFSET',
    'Tool_Offset',
    'UF',
    'UT',
    'UFRAME_NUM',
    'UTOOL_NUM',
    'UNLOCK',
    'WAIT',
    'X',
    'Y',
    'Z',
    'W',
    'P',
    'R',
    'STRLEN',
    'SUBSTR',
    'FINDSTR',
    'VOFFSET',
    'PROG',
    'ATTR',
    'MN',
    'POS',
]

number = [RE(r"[1-9][0-9]*")]

symbol = [RE(r":[^\]]+")]

class built_in:
    default_text = DELIMITER
    word_groups = [('number', number), ('symbol', symbol)]

class built_in0:
    default_text = DELIMITER
    word_groups = [('number', number), ('symbol', symbol)]
    delimited_ranges = [('string', RE(r"\""), [RE(r"\"")])]
built_in0.__name__ = 'built_in'

keyword0 = [RE(r"/(PROG|ATTR|MN|POS|END)\b")]

keyword1 = [RE(r"(CALL|RUN|POINT_LOGIC|LBL)\b")]

keyword2 = [RE(r"\b(ACC|CNT|Skip|Offset|PSPD|RT_LD|AP_LD|Tool_Offset)")]

number0 = [RE(r"\d+(sec|msec|mm/sec|cm/min|inch/min|deg/sec|mm|in|cm)?\b")]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

number1 = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

variable = [RE(r"\$[A-Za-z0-9_]+")]

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('keyword', keyword0),
    ('keyword', keyword1),
    ('keyword', keyword2),
    ('number', number0),
    ('number', number1),
    ('variable', variable),
]

delimited_ranges = [
    ('built_in', RE(r"(AR|P|PAYLOAD|PR|R|SR|RSR|LBL|VR|UALM|MESSAGE|UTOOL|UFRAME|TIMER|    TIMER_OVERFLOW|JOINT_MAX_SPEED|RESUME_PROG|DIAG_REC)\["), [RE(r"\]")], built_in),
    ('built_in', RE(r"(AI|AO|DI|DO|F|RI|RO|UI|UO|GI|GO|SI|SO)\["), [RE(r"\]")], built_in0),
    ('comment', RE(r"//"), [RE(r"[;$]")], comment),
    ('comment', RE(r"!"), [RE(r"[;$]")], comment),
    ('comment', RE(r"--eg:"), [RE(r"$")], comment),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('string', RE(r"'"), [RE(r"'")]),
]
