# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: twig.js
name = 'Twig'
file_patterns = ['*.twig', '*.craftcms']

flags = re.IGNORECASE | re.MULTILINE

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]),
    ]

keyword = """
    autoescape block do embed extends filter flush for if import include
    macro sandbox set spaceless use verbatim endautoescape endblock
    enddo endembed endextends endfilter endflush endfor endif endimport
    endinclude endmacro endsandbox endset endspaceless enduse
    endverbatim
    """.split()

class name0:
    default_text_color = DELIMITER
    rules = [('keyword', keyword)]
name0.__name__ = 'name'

class name2:
    default_text_color = DELIMITER
    rules = [('keyword', keyword), ('name', RE(r"\w+"), [RE(r"\B|\b")], name0)]
name2.__name__ = 'name'

keyword1 = """
    abs batch capitalize convert_encoding date date_modify default
    escape first format join json_encode keys last length lower merge
    nl2br number_format raw replace reverse round slice sort split
    striptags title trim upper url_encode
    """.split()

name3 = """
    attribute block constant cycle date dump include max min parent
    random range source template_from_string
    """.split()

class _group3:
    default_text_color = DELIMITER
    rules = [
        ('name', name3),
        ('keyword', name3),
        ('params', RE(r"\("), [RE(r"\)")]),
    ]

_group30 = ('_group3', RE(r"\b(?:attribute|block|constant|cycle|date|dump|include|max|min|parent|random|range|source|template_from_string)"), [RE(r"(?=%})")], _group3)

class _group2:
    default_text_color = DELIMITER
    rules = [('keyword', keyword1), _group30]

_group20 = ('_group2', RE(r"\|[A-Za-z_]+:?"), [RE(r"(?=%})")], _group2)

class _group1:
    default_text_color = DELIMITER
    ends_with_parent = True
    rules = [_group20, _group30]

class template_tag:
    default_text_color = DELIMITER
    rules = [('name', name2, [RE(r"(?=%})")], _group1)]
template_tag.__name__ = 'template-tag'

class template_variable:
    default_text_color = DELIMITER
    rules = [_group20, _group30]
template_variable.__name__ = 'template-variable'

rules = [
    ('comment', RE(r"\{#"), [RE(r"#}")], comment),
    ('template-tag', RE(r"\{%"), [RE(r"%}")], template_tag),
    ('template-variable', RE(r"\{\{"), [RE(r"}}")], template_variable),
]
