# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: typescript.js
name = 'TypeScript'
file_patterns = ['*.typescript', '*.ts']

literal = ['true', 'false', 'null', 'undefined', 'NaN', 'Infinity']

keyword = [
    'in',
    'if',
    'for',
    'while',
    'finally',
    'var',
    'new',
    'function',
    'do',
    'return',
    'void',
    'else',
    'break',
    'catch',
    'instanceof',
    'with',
    'throw',
    'case',
    'default',
    'try',
    'this',
    'switch',
    'continue',
    'typeof',
    'delete',
    'let',
    'yield',
    'const',
    'class',
    'public',
    'private',
    'protected',
    'get',
    'set',
    'super',
    'static',
    'implements',
    'enum',
    'export',
    'import',
    'declare',
    'type',
    'namespace',
    'abstract',
]

built_in = [
    'eval',
    'isFinite',
    'isNaN',
    'parseFloat',
    'parseInt',
    'decodeURI',
    'decodeURIComponent',
    'encodeURI',
    'encodeURIComponent',
    'escape',
    'unescape',
    'Object',
    'Function',
    'Boolean',
    'Error',
    'EvalError',
    'InternalError',
    'RangeError',
    'ReferenceError',
    'StopIteration',
    'SyntaxError',
    'TypeError',
    'URIError',
    'Number',
    'Math',
    'Date',
    'String',
    'RegExp',
    'Array',
    'Float32Array',
    'Float64Array',
    'Int16Array',
    'Int32Array',
    'Int8Array',
    'Uint16Array',
    'Uint32Array',
    'Uint8Array',
    'Uint8ClampedArray',
    'ArrayBuffer',
    'DataView',
    'JSON',
    'Intl',
    'arguments',
    'require',
    'module',
    'console',
    'window',
    'document',
    'any',
    'number',
    'boolean',
    'string',
    'void',
]

meta = [RE(r"^\s*['\"]use strict['\"]")]

class string:
    default_text = DELIMITER
    delimited_ranges = [('subst', RE(r"\$\{"), [RE(r"\}")])]

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

number = [RE(r"\b(0[bB][01]+)")]

number0 = [RE(r"\b(0[oO][0-7]+)")]

number1 = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

keyword0 = ['return', 'throw', 'case']

class regexp:
    default_text = DELIMITER
    delimited_ranges = [('_group9', RE(r"\["), [RE(r"\]")])]

class _group5:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0)]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
        ('regexp', RE(r"\/"), [RE(r"\/[gimuy]*")], regexp),
    ]

title = [RE(r"[A-Za-z$_][0-9A-Za-z$_]*")]

class params:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
    ]
    delimited_ranges = [
        ('comment', RE(r"//"), [RE(r"$")], comment),
        ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ]

class function:
    default_text = DELIMITER
    word_groups = [
        ('literal', literal),
        ('keyword', keyword),
        ('built_in', built_in),
        ('title', title),
    ]
    delimited_ranges = [('params', RE(r"\("), [RE(r"(?=\))")], params)]

keyword1 = ['interface', 'extends']

class _group15:
    default_text = DELIMITER
    word_groups = [('keyword', keyword1)]

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('built_in', built_in),
    ('meta', meta),
    ('number', number),
    ('number', number0),
    ('number', number1),
]

delimited_ranges = [
    ('string', RE(r"'"), [RE(r"'")]),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('string', RE(r"`"), [RE(r"`")], string),
    ('comment', RE(r"//"), [RE(r"$")], comment),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('_group5', RE(r"(!|!=|!==|%|%=|&|&&|&=|\*|\*=|\+|\+=|,|-|-=|/=|/|:|;|<<|<<=|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\?|\[|\{|\(|\^|\^=|\||\|=|\|\||~|\b(case|return|throw)\b)\s*"), [RE(r"\B|\b")], _group5),
    ('function', RE(r"function"), [RE(r"(?=[\{;])")], function),
    ('_group13', RE(r"\b(constructor)"), [RE(r"(?=\{)")]),
    ('_group14', RE(r"\b(module)"), [RE(r"(?=\{)")]),
    ('_group15', RE(r"\b(interface)"), [RE(r"(?=\{)")], _group15),
]
