# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: vala.js
name = 'Vala'
file_patterns = ['*.vala']

literal = ['false', 'true', 'null']

keyword = [
    'char',
    'uchar',
    'unichar',
    'int',
    'uint',
    'long',
    'ulong',
    'short',
    'ushort',
    'int8',
    'int16',
    'int32',
    'int64',
    'uint8',
    'uint16',
    'uint32',
    'uint64',
    'float',
    'double',
    'bool',
    'struct',
    'enum',
    'string',
    'void',
    'weak',
    'unowned',
    'owned',
    'async',
    'signal',
    'static',
    'abstract',
    'interface',
    'override',
    'while',
    'do',
    'for',
    'foreach',
    'else',
    'switch',
    'case',
    'break',
    'default',
    'return',
    'try',
    'catch',
    'public',
    'private',
    'protected',
    'internal',
    'using',
    'new',
    'this',
    'get',
    'set',
    'const',
    'stdout',
    'stdin',
    'stderr',
    'var',
]

built_in = ['DBus', 'GLib', 'CCode', 'Gee', 'Object']

keyword0 = ['class', 'interface', 'delegate', 'namespace']

title = [RE(r"[a-zA-Z_]\w*")]

class class0:
    default_text = DELIMITER
    word_groups = [('keyword', keyword0), ('title', title)]
class0.__name__ = 'class'

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text = DELIMITER
    word_groups = [('doctag', doctag)]

number = [RE(r"(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)")]

word_groups = [
    ('literal', literal),
    ('keyword', keyword),
    ('built_in', built_in),
    ('number', number),
]

delimited_ranges = [
    ('class', RE(r"\b(class|interface|delegate|namespace)"), [RE(r"(?={)")], class0),
    ('comment', RE(r"//"), [RE(r"$")], comment),
    ('comment', RE(r"/\*"), [RE(r"\*/")], comment),
    ('string', RE(r"\"\"\""), [RE(r"\"\"\"")]),
    ('string', RE(r"'"), [RE(r"'")]),
    ('string', RE(r"\""), [RE(r"\"")]),
    ('meta', RE(r"^#"), [RE(r"$")]),
]
