# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: vbscript-html.js
name = 'VBScript in HTML'
file_patterns = ['*.vbscript-html']


word_groups = []

delimited_ranges = [('_group0', RE(r"<%"), [RE(r"%>")], 'vbscript')]
