# -*- coding: UTF-8 -*-
# Syntax definition automatically generated by hljs2xt.py
# source: yaml.js
name = 'YAML'
file_patterns = ['*.yaml', '*.yml', '*.YAML', '*.yaml']

flags = re.IGNORECASE | re.MULTILINE

literal = """
    { } true false yes no Yes No True False null
    """.split()

attr = [RE(r"^[ \-]*[a-zA-Z_][\w\-]*:")]

attr0 = [RE(r"^[ \-]*\"[a-zA-Z_][\w\-]*\":")]

attr1 = [RE(r"^[ \-]*'[a-zA-Z_][\w\-]*':")]

meta = [RE(r"^---s*$")]

class string:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': '\\\\[\\s\\S]', 'relevance': 0},
        ('template-variable', RE(r"{{"), [RE(r"}}")]),
        ('template-variable', RE(r"%{"), [RE(r"}")]),
    ]

type = [RE(r"!![a-zA-Z_]\w*")]

meta0 = [RE(r"&[a-zA-Z_]\w*$")]

meta1 = [RE(r"\*[a-zA-Z_]\w*$")]

bullet = [RE(r"^ *-")]

class string0:
    default_text_color = DELIMITER
    rules = []
string0.__name__ = 'string'

doctag = [RE(r"(?:TODO|FIXME|NOTE|BUG|XXX):")]

class comment:
    default_text_color = DELIMITER
    rules = [
        # ignore {'begin': {'pattern': "\\b(a|an|the|are|I|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|like)\\b", 'type': 'RegExp'}},
        ('doctag', doctag),
    ]

number = [
    RE(r"(?:\b0[xX][a-fA-F0-9]+|(?:\b\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)"),
]

rules = [
    ('literal', literal),
    ('attr', attr),
    ('attr', attr0),
    ('attr', attr1),
    ('meta', meta),
    ('string', RE(r"[\|>] *$"), [RE(r"(?=^[ \-]*[a-zA-Z_][\w\-]*:)")], string),
    ('_group0', RE(r"<%[%=-]?"), [RE(r"[%-]?%>")], 'ruby'),
    ('type', type),
    ('meta', meta0),
    ('meta', meta1),
    ('bullet', bullet),
    ('string', RE(r"'"), [RE(r"'")], string0),
    ('string', RE(r"\""), [RE(r"\"")], string0),
    ('comment', RE(r"#"), [RE(r"$")], comment),
    ('number', number),
]
